### ISSUE TITLE
Error with tcpReassemblyMsgReadyCallback on Windows (Visual Studio)

### ISSUE THREAD

**Issue by MinusPL** [seladb/PcapPlusPlus#515] opened 2020-08-10 14:02 UTC
Hello, I tried to use TcpReassembly example to make my own program use TcpReassembly class, but for some reason Visual Studio 19 has some issues with callback function tcpReassemblyMsgReadyCallback.

when creating TcpReassembly instance it tells me that arguments does not match. I'm using PcapPlusPlus v19.12 and I'm using Windows 10 2004 with MSVC 19.26.28805 for x86.
I know this example was designed for linux (or rather POSIX systems, but there shouldn't be any problem with compiling it on Windowes after removing getopt code since all other things seem to be the same on Windows and POSIX systems.

Can you tell me what I'm doing wrong? (code is almost identical to one in example for now, just getopt features were commented out and options were hardcoded to test)

**Comment by seladb** [comment] 2020-08-10 17:38
The TCP example code works on VS 2019 as you can see in the [CI](https://ci.appveyor.com/project/seladb/pcapplusplus/branch/master) so I'm not sure what's the issue in your environment.

Are you using the pre-compiled binaries or building PcapPlusPlus from source?

**Comment by MinusPL** [comment] 2020-08-11 13:25
I'm using pre-compiled binaries iirc.
Only thing I noticed is that in this TcpReassembly constructor it only has problems with tcpReassemblyMsgReadyCallback, both start and end connection callbacks are working properly.

**Comment by seladb** [comment] 2020-08-12 09:51
Can you please try with the latest code from `master`? 

I don't recall any specific issues with TCP reassembly in the latest release of PcapPlusPlus (v19.12), but changes were made to that code since then.

Or if you can wait few days, a new PcapPlusPlus release will come out this week or next week (v20.08) so you can try it also. Here is a preview for that release: https://ci.appveyor.com/api/buildjobs/jqaxsppb89wulqrb/artifacts/VS-Package.zip

**Comment by MinusPL** [comment] 2020-08-12 10:32
I think I'll wait, for now I just used Wireshark and got data I needed through it. After new release comes out I'll check if I still have issue and send another comment. Thanks for your time.

**Comment by seladb** [comment] 2020-08-12 10:48
Sure. You can try the new release in the link I shared.

Should we keep this issue open or can we close it?

**Comment by MinusPL** [comment] 2020-08-12 11:04
It would be better to leave it open I guess. If everything works properly after I test it we can close it.

**Comment by seladb** [comment] 2020-08-25 07:32
I've just release [v20.08](https://github.com/seladb/PcapPlusPlus/releases/tag/v20.08). Can you please check again?

**Comment by SebBil** [comment] 2020-08-25 08:21
I had the same problem. Solution is to check the declaration of the Callback methods in the TcpReassembly.h and the example of the TcpReassembly Callback methods.
Declaration in header: (int side, const TcpStreamData& tcpData, void* userCookie);
Declaration in example:  tcpReassemblyMsgReadyCallback(int8_t sideIndex, const TcpStreamData& tcpData, void* userCookie)
The side index doesn't match.

**Comment by seladb** [comment] 2020-08-26 07:08
Thanks @SebBil , indeed I think that was fixed at some point. So I'm assuming the issue is gone with the newest release, right?

**Comment by seladb** [comment] 2020-08-29 21:48
Let me close this issue for now. Please reopen if needed

**Closed by seladb** 2020-08-29 21:48 UTC
Labels: question
