### ISSUE TITLE
DPDK Filter Example

### ISSUE THREAD

**Issue by AqsaKashaf** [seladb/PcapPlusPlus#633] opened 2021-04-19 19:36 UTC
Hi, I am using dpdk 18.11. When I try to run DPDK filter example, i get the following error;
```
sudo ./DpdkTrafficFilter -d 0
EAL: Detected 20 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:43:00.0 on NUMA socket 1
EAL:   probe driver: 8086:1528 net_ixgbe
EAL: PCI device 0000:43:00.1 on NUMA socket 1
EAL:   probe driver: 8086:1528 net_ixgbe
ixgbe_alloc_rx_queue_mbufs(): RX mbuf alloc failed queue_id=31
ixgbe_dev_rx_queue_start(): Could not alloc mbuf for queue:31
ixgbe_dev_start(): Unable to start rxtx queues
ixgbe_dev_start(): failure in ixgbe_dev_start(): -1
Failed to start device 0. Error is -5
failed to start device 0

Application terminated in error: Couldn't open DPDK device #0, PMD 'net_ixgbe'
```

I tried changing the mbuf pool size parameter but did not work

**Comment by seladb** [comment] 2021-05-03 03:02
Is it working if you try to run DPDK examples without PcapPlusPlus?

**Comment by AqsaKashaf** [comment] 2021-05-03 03:12
YesOn May 2, 2021 11:02 PM, seladb ***@***.***> wrote:
Is it working if you try to run DPDK examples without PcapPlusPlus?

**Comment by seladb** [comment] 2021-05-03 03:20
The error it gives is that there are no free hugepages, so it cannot allocate RX mbufs. You can run this command to check how many free hugepages you have: `grep HugePages_ /proc/meminfo`:
https://access.redhat.com/solutions/320303

**Comment by seladb** [comment] 2021-05-17 06:51
@AqsaKashaf what should we do with this issue?

**Comment by AqsaKashaf** [comment] 2021-05-19 14:58
Hi, So I have hugepages allocated. 

This is what i get:
```
cat /proc/meminfo | grep Huge
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
HugePages_Total:    1024
HugePages_Free:     1009
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
```

**Comment by AqsaKashaf** [comment] 2021-05-19 14:59
and this is what I get: 
```
sudo ./DpdkTrafficFilter -d 0
EAL: Detected 40 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:42:00.0 on NUMA socket 1
EAL:   probe driver: 8086:1584 net_i40e
EAL: PCI device 0000:43:00.0 on NUMA socket 1
EAL:   probe driver: 8086:1528 net_ixgbe
EAL: PCI device 0000:43:00.1 on NUMA socket 1
EAL:   probe driver: 8086:1528 net_ixgbe
EAL: PCI device 0000:44:00.0 on NUMA socket 1
EAL:   probe driver: 8086:1584 net_i40e
ixgbe_alloc_rx_queue_mbufs(): RX mbuf alloc failed queue_id=31
ixgbe_dev_rx_queue_start(): Could not alloc mbuf for queue:31
ixgbe_dev_start(): Unable to start rxtx queues
ixgbe_dev_start(): failure in ixgbe_dev_start(): -1
Failed to start device 0. Error is -5
failed to start device 0

Application terminated in error: Couldn't open DPDK device #0, PMD 'net_ixgbe'
```

**Comment by AqsaKashaf** [comment] 2021-05-19 15:00
I am able to run othe DPDK applications, such as MoonGen, or testpmd, etc.

**Comment by seladb** [comment] 2021-05-25 05:36
@AqsaKashaf maybe the number of free hugepages isn't enough? You can try to open the device with less queues (or more hugepages) and see if that fixes the issue

**Comment by AqsaKashaf** [comment] 2021-05-26 14:11
you mean changing the mbuf pool size parameter? I have tried that before, but it did not help. I can try it again

**Comment by seladb** [comment] 2021-05-29 06:32
I'd suggest trying to open the device with less queues (it seems that currently you're using 32). I think that each queue consumes a certain amount of mbufs, so maybe the total number of mbufs required is too much 🤔 
I'd suggest opening 1 queue for start and see if it's working.

**Comment by seladb** [comment] 2021-06-08 08:38
@AqsaKashaf should we keep this issue open or close it?

**Comment by seladb** [comment] 2021-06-15 07:02
@AqsaKashaf I'm closing this issue for now, please repoen if needed

**Closed by seladb** 2021-06-15 07:02 UTC

**Comment by fattaholmanan** [comment] 2021-06-25 08:03
I have the same issue! I tried to reduce the number of `cores` and `pool size`, but still it doesn't work. 
```bash
sudo ./Bin/DpdkTrafficFilter -c 011 -d 0 -i 10.100.1.97
EAL: Detected 12 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: No available hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:01:00.0 on NUMA socket 0
EAL:   probe driver: 8086:10fb net_ixgbe
EAL: PCI device 0000:01:00.1 on NUMA socket 0
EAL:   probe driver: 8086:10fb net_ixgbe
ixgbe_alloc_rx_queue_mbufs(): RX mbuf alloc failed queue_id=7
ixgbe_dev_rx_queue_start(): Could not alloc mbuf for queue:7
ixgbe_dev_start(): Unable to start rxtx queues
ixgbe_dev_start(): failure in ixgbe_dev_start(): -1
Failed to start device 0. Error is -5
failed to start device 0

Application terminated in error: Couldn't open DPDK device #0, PMD 'net_ixgbe'
```

**Comment by seladb** [comment] 2021-06-28 07:12
@fattaholmanan Since I can't reproduce it on my system, can you please try to discover where this error comes from in the DPDK source code? It says the error is -5 but I don't know what it is...

**Comment by fattaholmanan** [comment] 2021-06-28 09:09
@seladb  thanks for your response. I managed to trace the error to DPDK library (I'm using version `19.11.8`)
I found that in line 1654 of file `rte_ethdev.c` variable `diag` is set to `-5`.
```c
int
rte_eth_dev_start(uint16_t port_id)
{
	struct rte_eth_dev *dev;
	struct rte_eth_dev_info dev_info;
	int diag;
	int ret;

	....

	/* Lets restore MAC now if device does not support live change */
	if (*dev_info.dev_flags & RTE_ETH_DEV_NOLIVE_MAC_ADDR)
		rte_eth_dev_mac_restore(dev, &dev_info);

	diag = (*dev->dev_ops->dev_start)(dev);
        if (diag == 0)
		dev->data->dev_started = 1;
	else
		return eth_err(port_id, diag);

```
Please let me know if I can provide you more information.

**Comment by seladb** [comment] 2021-06-28 09:48
thanks @fattaholmanan ! I think we need to dig deeper into what `diag == -5` means. Why does `dev_start` return that error?

**Comment by fattaholmanan** [comment] 2021-06-28 10:00
@seladb  I don't have any experience working with DPDK. I try to find out...
