### ISSUE TITLE
Crash due malformed packet data

### ISSUE THREAD

**Issue by alexdrobinsky** [seladb/PcapPlusPlus#864] opened 2022-04-03 13:02 UTC
Hi ,

I found following issue - if for example link layer type set to raw but packet data isn't actual IP layer but rather some junk, 
Packet.cpp crashes in following place:
function: setRawPacket, those lines -
	if (curLayer != NULL &&  curLayer->getOsiModelLayer() > parseUntilLayer)
	{
		m_LastLayer = curLayer->getPrevLayer();
		delete curLayer;
		**m_LastLayer->m_NextLayer = NULL;**
	}
[debug.gz](https://github.com/seladb/PcapPlusPlus/files/8404545/debug.gz)
The reason behind it -  because current layer is a first layer,  previous layer is null. m_LastLayer turns to null and as result,  line m_LastLayer->m_NextLayer causes crash.
This issue would happen probably with every packet if link type passed to RawPacket constructor is incorrect. 
I attached pcap with extension changed to zip, please change back it to pcap & force usage of raw link type during packet parsing.

**Comment by seladb** [comment] 2022-04-04 06:29
@alexdrobinsky thanks for reporting this issue! 
I think the solution is quite simple - we need to add a null check before setting `m_LastLayer->m_NextLayer = NULL`, right?
Would you consider opening a PR with the fix? Also - it would be nice to add a test for it (maybe [here](https://github.com/seladb/PcapPlusPlus/blob/master/Tests/Packet%2B%2BTest/Tests/PacketTests.cpp)). Unfortunately I cannot open the file you attached but I assume it contains a packet that reproduces the issue?

**Comment by alexdrobinsky** [comment] 2022-04-04 06:56
Yes, attached pcap should reproduce scenario. I will test is simple check is sufficient.

**Comment by alexdrobinsky** [comment] 2022-04-04 07:14
Another try to upload test pcap :) This file isn't a real gz archive -
please rename the extension to pcap.

пн, 4 апр. 2022 г. в 09:29, seladb ***@***.***>:

**Comment by alexdrobinsky** [comment] 2022-04-04 07:42
The fix looks like following :
**m_LastLayer->m_NextLayer = NULL;** should be replaced with:
        if (m_LastLayer != nullptr) {
            m_LastLayer->m_NextLayer = NULL;
        } else {
            // This means we failed to parse first layer and already deleted it, hence we must set it to null,
            m_FirstLayer = nullptr;
        }

I checked that parser ignored malformed packets and correctly parsed rest of data :)

**Comment by seladb** [comment] 2022-04-06 06:52
Thanks for providing the solution! Feel free to open a PR and we can discuss there more.

Few comments:
- I'm not sure we should set `m_FirstLayer = NULL` 🤔 . If the first layer can't be parsed we just create a `PayloadLayer` as you can see [here](https://github.com/seladb/PcapPlusPlus/blob/a817631a3ea4742b24ef1e6941fee26642880071/Packet%2B%2B/src/Packet.cpp#L706), so there's always a fallback 
- PcapPlusPlus doesn't officially supports C++11 yet (we're planning to migrate soon), so instead of `nullptr` we use `NULL`

**Comment by alexdrobinsky** [comment] 2022-04-15 07:06
m_FirstLayer is actually curLayer, so when we delete it - m_FirstLayer
points to deallocated memory, before I set it to null, the code was
crashing in other place, so I added it out of necessity :)
Sorry for delayed response !

ср, 6 апр. 2022 г. в 09:52, seladb ***@***.***>:

**Comment by seladb** [comment] 2022-04-22 06:16
@alexdrobinsky I can't reproduce the issue with the pcap file you attached. I tried to run [`PcapPrinter`](https://github.com/seladb/PcapPlusPlus/tree/master/Examples/PcapPrinter) with this pcap file and it doesn't crash:

```shell
$ Bin/PcapPrinter ~/Downloads/debug.pcap 
File summary:
~~~~~~~~~~~~~
   File name: /home/seladb/Downloads/debug.pcap
   File size: 46209 bytes
   Link layer type: Raw IP (12)

Packet length: 38 [Bytes], Arrival time: 2013-01-24 11:14:59.973218000
Payload Layer, Data length: 38 [Bytes]

Packet length: 194 [Bytes], Arrival time: 2013-01-24 11:15:00.670839000
IPv6 Layer, Src: fe80::d0e3:ae31:ef32:3d60, Dst: ff02::6ecb:9925
UDP Layer, Src port: 53816, Dst port: 1900
Payload Layer, Data length: 146 [Bytes]

Packet length: 38 [Bytes], Arrival time: 2013-01-24 11:15:01.989403000
Payload Layer, Data length: 38 [Bytes]

Packet length: 40 [Bytes], Arrival time: 2013-01-24 11:15:02.777854000
IPv4 Layer, Src: 182.15.248.128, Dst: 174.99.151.43
TCP Layer, [ACK], Src port: 119, Dst port: 60344

Packet length: 40 [Bytes], Arrival time: 2013-01-24 11:15:02.777893000
IPv4 Layer, Src: 174.99.151.43, Dst: 182.15.248.128
TCP Layer, [ACK], Src port: 60344, Dst port: 119

Packet length: 28 [Bytes], Arrival time: 2013-01-24 11:15:03.344188000
Payload Layer, Data length: 28 [Bytes]

Packet length: 194 [Bytes], Arrival time: 2013-01-24 11:15:03.670701000
IPv6 Layer, Src: fe80::d0e3:ae31:ef32:3d60, Dst: ff02::6ecb:9925
UDP Layer, Src port: 53816, Dst port: 1900
Payload Layer, Data length: 146 [Bytes]

Packet length: 42 [Bytes], Arrival time: 2013-01-24 11:15:04.005242000
Payload Layer, Data length: 42 [Bytes]

Packet length: 38 [Bytes], Arrival time: 2013-01-24 11:15:04.020558000
Payload Layer, Data length: 38 [Bytes]

Packet length: 46 [Bytes], Arrival time: 2013-01-24 11:15:04.036655000
Payload Layer, Data length: 46 [Bytes]

Packet length: 28 [Bytes], Arrival time: 2013-01-24 11:15:05.482628000
Payload Layer, Data length: 28 [Bytes]

Packet length: 28 [Bytes], Arrival time: 2013-01-24 11:15:05.482874000
Payload Layer, Data length: 28 [Bytes]

Packet length: 52 [Bytes], Arrival time: 2013-01-24 11:15:05.482918000
IPv4 Layer, Src: 174.99.151.43, Dst: 174.99.151.224
TCP Layer, [SYN], Src port: 60354, Dst port: 25

Packet length: 52 [Bytes], Arrival time: 2013-01-24 11:15:05.483126000
IPv4 Layer, Src: 174.99.151.224, Dst: 174.99.151.43
TCP Layer, [SYN, ACK], Src port: 25, Dst port: 60354

...
...
```

**Comment by alexdrobinsky** [comment] 2022-04-24 12:20
Hi , just to be sure, I upgraded my local version of pcapPlusPlus to the
latest and checked
behaviour without my patch - my application crashes in setRawPacket,
behaviour after patch - application works as intended.
However, it could be possible that I sent the wrong pcap , so I attached a
fresh version (gzipped ).
Hopefully, gitlab will not remove it as usual.

пт, 22 апр. 2022 г. в 09:16, seladb ***@***.***>:

**Comment by seladb** [comment] 2022-04-25 07:00
@alexdrobinsky I cannot see the file, maybe you can log in to your GitHub account and upload the file to the issue directly?

Also - can you paste the code that reproduces this issue? Maybe PcapPrinter cannot reproduce it?

**Comment by alexdrobinsky** [comment] 2022-04-25 11:51
[debug.pcap.gz](https://github.com/seladb/PcapPlusPlus/files/8554178/debug.pcap.gz)

...
        pcpp::LinkLayerType layerType;
        if (!firstLayerTypeValid(commonData->firstlayer(), layerType)) {
            return;
        }

        timeval timestamp{};
        timestamp.tv_sec = commonData->timestamp().seconds();
        timestamp.tv_usec = commonData->timestamp().nanoseconds() / 1000;

        // construct rawPAcket. indicate that the data pointed should not be freed at destruction
        pcpp::RawPacket rawPacket((const unsigned char *) rawData, commonData->rawdata().size(), timestamp, false,
                                  layerType);

        // parse the raw packet into a parsed packet. parse up to layer 4 (inclusive)
        pcpp::Packet parsedPacket(&rawPacket, pcpp::OsiModelTransportLayer);

        if (parsedPacket.getFirstLayer() == nullptr)  {
            commonData->set_firstlayer(proto::FirstLayerType::firstLayerTypeUnknown);
            return;
        }

// LinkLayerType in this case is LINKTYPE_DLT_RAW1

**Comment by seladb** [comment] 2022-04-26 08:00
@alexdrobinsky the code you provided misses some parts and can't run on its own so I modified it a bit. I took the first packet in the pcap file you provided:

```cpp
void test()
{
	timeval time;
	gettimeofday(&time, NULL);

	pcpp::LinkLayerType layerType = pcpp::LINKTYPE_DLT_RAW1;

	// This is a hex stream of the first packet in the file you provided
	std::string packetStream = "45000028314a40008006fc8bc0a80e02c7073748ebc800507b67c69889d873c65010fba4bb7d0000";

	uint8_t packetBytes[1024];
	size_t packetSize = pcpp::hexStringToByteArray(packetStream, packetBytes, 1024);

	// construct rawPAcket. indicate that the data pointed should not be freed at destruction
	pcpp::RawPacket rawPacket((const unsigned char *) packetBytes, packetSize, time, false, layerType);

	// parse the raw packet into a parsed packet. parse up to layer 4 (inclusive)
	pcpp::Packet parsedPacket(&rawPacket, pcpp::OsiModelTransportLayer);

	if (parsedPacket.getFirstLayer() == NULL)  {
		std::cout << "First layer is null\n";
	}

	std::cout << "First layer is NOT null\n";
}
```

This code doesn't crash and prints the following output:

```shell
First layer is NOT null
```

I'm still not sure how to reproduce this issue 😕

**Comment by seladb** [comment] 2022-04-26 15:44
Sure @alexdrobinsky we can close this issue now. Please feel free to reopen it if you find code that can reproduce it outside of your system

**Closed** 2022-04-26 15:45 UTC
Labels: bug
