### ISSUE TITLE
PcapSplitter go wrong when capture length is smaller than frame length

### ISSUE THREAD

**Issue by Sai10032** [seladb/PcapPlusPlus#49] opened 2017-03-03 09:39 UTC
when the payload have been nulled out，the frame length is the capture length after split the pcap file.

**Comment by seladb** [comment] 2017-03-03 19:51
Could you please attach a pcap file with an example of such packets? It'll help me debug this issue

**Comment by Sai10032** [comment] 2017-03-03 20:06
http://pages.cs.wisc.edu/~tbenson/IMC10_Data.html this is where i get the pcap file On 2017-03-04 03:51 , seladb Wrote: Could you please attach a pcap file with an example of such packets? It'll help me debug this issue — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by seladb** [comment] 2017-03-03 20:15
Thanks! There are 2 pcap files on that page, which one is failing? In addition - could you please write the PcapSplitter command you're trying to run?

**Comment by Sai10032** [comment] 2017-03-03 20:21
everyone is same result, you could test it. i run it like 'pcapspliter -f input.pcap -o outdir -m connection' On 2017-03-04 04:15 , seladb Wrote: Thanks! There are 2 pcap files on that page, which one is failing? In addition - could you please write the PcapSplitter command you're trying to run? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Sai10032** [comment] 2017-03-03 20:24
i checked the code and found that you may assume capture length and frame length is equal

**Comment by seladb** [comment] 2017-03-03 22:02
Cool thanks for the info. Do you want to prepare a fix it and create a pull request or do you prefer I do the fix?

**Comment by seladb** [comment] 2017-03-03 22:43
Still can't reproduce it. Downloaded one the the files but it contains many 100MB pcap files. Can you please direct me to a specific one causing the problem?
In addition - can you direct me to the place in the code you think is problematic?

**Comment by Sai10032** [comment] 2017-03-04 09:02
I have create a pull request

**Comment by seladb** [comment] 2017-03-04 20:54
Merged your pull request: #51 
Thanks a lot for finding and fixing this bug!

**Closed by seladb** 2017-03-04 20:54 UTC
