### ISSUE TITLE
SIP messages can't be parsed

### ISSUE THREAD

**Issue by JimG777** [seladb/PcapPlusPlus#67] opened 2017-09-21 02:14 UTC
Hi,

There are some probable typos in SipLayer.cpp. The last index for comparison is not incremented for SUBSCRIBE and MESSAGE, therefore they are never decoded as SIP messages.

Line 235: ... data[8] == ' ' should be data[9] == ' '
Line 260: ... data[6] == ' ' should be data[7] == ' '

James

**Comment by seladb** [comment] 2017-09-22 08:10
Thank you for finding the bug and pointing to the root caused. I just pushed a fix, please pull the latest code in master branch

**Closed by seladb** 2017-09-22 08:10 UTC
