### ISSUE TITLE
Compiling error in Windows msys2

### ISSUE THREAD

**Issue by zliucd** [seladb/PcapPlusPlus#1135] opened 2023-05-19 12:51 UTC
Hello,

There are some compiling errors of building PcapPlusPlus in Windows msys2 environment. Dependencies were set ok using `configure-windows-mingw.bat`, e.g., mingw64, msys2 and WinPcap.   

=== **Environment** ===
Windows 11 x86_64
msys2, g++ 11
PcapPlusPlus:  an old version released in late 2021.

=== Error **messages** ===
See error messages as below, Are there some devel packages missing? 

![pcap++](https://github.com/seladb/PcapPlusPlus/assets/89120271/b37dc5e7-0f9f-4aec-8f7a-f816d8cbd126)

Thanks a lot.

**Comment by seladb** [comment] 2023-05-29 02:24
Can you please share the parameters you provide to `configure-windows-mingw.bat`?
It looks like there is the paths provided to `--mingw-home` or `--msys-home` are wrong, hence it can't find the symbols `_popen` and `GetSystemInfo`

**Comment by seladb** [comment] 2023-06-08 06:38
@zliucd did you see my last comment/question?

**Comment by zliucd** [comment] 2023-06-08 08:09
@seladb  Sorry for late reply.  I'm not familiar with Windows and ```msys```, and I will try to provide more info you mentioned asap.  I  compiled PcapPlusPlus in vanilla ```msys``` settings without exporting  specific environment variables.

**Comment by seladb** [comment] 2023-07-09 22:12
@zliucd any update on this?

**Comment by zliucd** [comment] 2023-07-10 05:04
Hi,

Thanks for follow up. I just tried to build PcapPlusPlus in Windows
yesterday, but got same error message.  I'm not familiar with Windows
building, and try to use prebuilt shared binaries.

By using static libraries (libPcap++.a, libPacket++.a, libCommon++.a) and
libpcap.a in Linux,  PcapPlusPlus reported error messages that it wanted to
load libpcap.so.  But in OSX(M1), it went ok.

Thanks for your reply.

seladb ***@***.***> 于2023年7月10日周一 06:12写道：

**Comment by seladb** [comment] 2023-07-10 06:40
@zliucd if you build on Windows you need the Windows binaries, not the Linux ones...

**Comment by zliucd** [comment] 2023-07-10 23:57
By using static libraries (libPcap++.a, libPacket++.a, libCommon++.a) and
libpcap.a in Linux,  PcapPlusPlus reported error messages that it wanted to
load libpcap.so.  But in OSX(M1), it went ok.
-------------------------------

It's a different issue that is not related to Windows building.  You may
try to reproduce it.


seladb ***@***.***> 于2023年7月10日周一 14:40写道：

**Comment by seladb** [comment] 2023-07-15 02:01
I'm unsure how to reproduce it because it works well on my local machine and in [PcapPlusPlus CI](https://github.com/seladb/PcapPlusPlus/actions/runs/5482920145). Did you follow the instructions in [PcapPlusPlus web-site](https://pcapplusplus.github.io/docs/install)?

**Comment by seladb** [comment] 2023-08-08 02:01
@zliucd should we keep this issue open or can we close it?

**Comment by zliucd** [comment] 2023-08-08 10:28
@seladb   You may close the issue, though there are still some problems of compiling source code in my Windows machine. I can use prebuilt packages.

**Comment by seladb** [comment] 2023-08-09 05:49
Thanks @zliucd , sorry I couldn't help. You may follow PcapPlusPlus GitHub Action CI to see how we build from source there

**Closed by seladb** 2023-08-09 05:49 UTC
