### ISSUE TITLE
how can I compile a release version of vs2019 on Windows plateform based on the newest code？

### ISSUE THREAD

**Issue by angelyouyou** [seladb/PcapPlusPlus#623] opened 2021-04-06 16:44 UTC
https://github.com/seladb/PcapPlusPlus/releases/download/v20.08/pcapplusplus-20.08-windows-vs2019.zip

**Comment by seladb** [comment] 2021-04-06 20:21
Are you referring to the latest code from `master` or to the latest release (v20.08)?

For the code from `mater` you can see here: https://pcapplusplus.github.io/docs/install/build-source/vs

For the latest release: it already includes a release version of PcapPlusPlus libraries, please see `README.release` inside the zip file: `pcapplusplus-20.08-windows-vs2019.zip`

**Comment by angelyouyou** [comment] 2021-04-06 23:48
@seladb thanks very much.
Yes, I want to build the code from mater for vs 2019,  I got it.

**Comment by angelyouyou** [comment] 2021-04-07 08:06
@seladb 
After I run configure-windows-visual-studio.bat, then generated PcapPlusPlus\mk\vs2019\*.vcxproj.
 The *.vcxproj has some problems, the begging string is wrong, it caused visual studio failed to open the solution.

"﻿?xml version="1.0" encoding="utf-8"?>"

![image](https://user-images.githubusercontent.com/12936259/113831913-b0272a00-97ba-11eb-94ea-89f25c1d2a60.png)

**Comment by seladb** [comment] 2021-04-07 08:15
@angelyouyou can you please specify which `*.vcxproj` is causing this issue?

I cannot reproduce it on my local machine and it also works in [GitHub Actions CI](https://github.com/seladb/PcapPlusPlus/runs/2277003807?check_suite_focus=true)

**Comment by angelyouyou** [comment] 2021-04-07 08:18
> @angelyouyou can you please specify which `*.vcxproj` is causing this issue?
> 
> I cannot reproduce it on my local machine and it also works in [GitHub Actions CI](https://github.com/seladb/PcapPlusPlus/runs/2277003807?check_suite_focus=true)

All of the *.vcxproj files on windows 10(2020H2).

**Comment by seladb** [comment] 2021-04-07 08:29
> All of the *.vcxproj files on windows 10(2020H2). Used cmd or terminal tool.

I have a Windows 10 (2004) machine and GitHub Actions CI runs Windows Server 2019 so unfortunately I don't have a way to debug this issue. Can you please try on an older Windows version and see if this issue is reproduced?
Also, if you can spend some time to debug this issue that would be great. I'd start with the configuration file: [`configure-windows-visual-studio.bat`](https://github.com/seladb/PcapPlusPlus/blob/master/configure-windows-visual-studio.bat)

**Comment by angelyouyou** [comment] 2021-04-07 08:31
> > All of the *.vcxproj files on windows 10(2020H2). Used cmd or terminal tool.
> 
> I have a Windows 10 (2004) machine and GitHub Actions CI runs Windows Server 2019 so unfortunately I don't have a way to debug this issue. Can you please try on an older Windows version and see if this issue is reproduced?
> Also, if you can spend some time to debug this issue that would be great. I'd start with the configuration file: [`configure-windows-visual-studio.bat`](https://github.com/seladb/PcapPlusPlus/blob/master/configure-windows-visual-studio.bat)

OK, I will try the bat later

**Comment by seladb** [comment] 2021-04-13 06:03
> Where should I add "echo" for the wrong begging tag for debugging in the configure-windows-visual-studio.bat.

I'm not sure I understand your question 🤔

**Comment by angelyouyou** [comment] 2021-04-15 05:23
I want to know where the vs2019*.vcxproj header tag information is written in [configure-windows-visual-studio.bat](https://github.com/seladb/PcapPlusPlus/blob/master/configure-windows-visual-studio.bat) , in order to add positioning information such as echo.

**Comment by seladb** [comment] 2021-04-15 07:02
the template `vcxproj` files are located here: https://github.com/seladb/PcapPlusPlus/tree/f94bbf8133a32033fcb80b765d543ce147f57a46/mk/vs
They include a few variables: `PUT_TOOLS_VERSION_HERE`, `PUT_WIN_TARGET_PLATFORM_HERE`, `PUT_PLATORM_TOOLSET_HERE`, etc.
These templates are replaced by `configure-windows-visual-studio.bat` here:
https://github.com/seladb/PcapPlusPlus/blob/master/configure-windows-visual-studio.bat#L94-L111

Maybe something is not working in this code?

**Comment by seladb** [comment] 2021-05-04 02:20
@angelyouyou should we keep this issue open or close it?

**Closed** 2021-05-10 10:58 UTC
Labels: question
