### ISSUE TITLE
Support for DPDK 17.02?

### ISSUE THREAD

**Issue by kaijunzhan** [seladb/PcapPlusPlus#52] opened 2017-04-16 06:56 UTC
Any plan to support DPDK 17.02? It looks like compiles with old versions (as it was mentioned in the README)

**Comment by seladb** [comment] 2017-04-17 06:02
I don't have it in my immediate plans although I can prioritize this if required by many people.
Another option is to try it yourself, shouldn't be much of a problem. What do you think?

**Comment by iGeneral** [comment] 2017-04-17 09:35
I use PcapPlusPlus + dpdk-17.02 without any problems.
For install you need to slightly modify PCAPPP_LIBS section in PcapPlusPlus.mk.dpdk

**Comment by seladb** [comment] 2017-04-17 18:14
Cool thanks, could you please attach the PcapPlusPlus.mk.dpdk you're using?

**Comment by iGeneral** [comment] 2017-04-28 12:58
**1)By default Compiling 'Pcap++Test' is failed.**
/tmp/PcapPlusPlus/Tests/Pcap++Test# make
g++ -L../../Common++/Lib/Debug -L/tmp/PcapPlusPlus/Dist -L/home/am/dpdk-17.02/build/lib -L/lib64  -msse -msse2 -msse3 -Wall -o "./Bin/Pcap++Test" Obj/main.o ../../3rdParty/debug-new/../../3rdParty/debug-new/debug_new.o -lPcap++ -lPacket++ -lCommon++ -lpcap -lpthread -Wl,--whole-archive -lrte_pmd_bond -lrte_pmd_vmxnet3_uio -lrte_pmd_virtio -lrte_pmd_enic -lrte_pmd_i40e -lrte_pmd_fm10k -lrte_pmd_ixgbe -lrte_pmd_e1000 -lrte_pmd_ring -lrte_pmd_af_packet -lethdev -lrte_eal -lrte_mbuf -lrte_mempool -lrte_malloc -lrte_ring -lrte_kvargs -lrte_hash -lrte_cmdline -lrt -lm -ldl -lpthread -Wl,--no-whole-archive
/usr/bin/ld: cannot find -lethdev
/usr/bin/ld: cannot find -lrte_malloc
collect2: error: ld returned 1 exit status
Makefile:59: recipe for target 'Pcap++Test' failed
make: *** [Pcap++Test] Error 1

**2) Modify libs line in .mk file**
# libs
 PCAPPP_LIBS += -Wl,--whole-archive -lrte_pmd_bond -lrte_pmd_vmxnet3_uio -lrte_pmd_virtio -lrte_pmd_enic -lrte_pmd_i40e -lrte_pmd_fm10k -lrte_pmd_ixgbe -lrte_net -lrte_pmd_e1000 -lrte_pmd_ring -lrte_pmd_af_packet -**lrte_ethdev** -lrte_eal -lrte_mbuf -lrte_mempool -lrte_ring -lrte_kvargs -lrte_hash -lrte_cmdline -lrt -lm -ldl -lpthread -Wl,--no-whole-archive

**3)Enjoy**

**Comment by mmanoj** [comment] 2017-04-29 09:55
Thanks for the support, however while run make all DPDK example giving below error. Any idea ?

/opt/dpdk/dpdk-stable-16.11.1/build/lib/librte_eal.a(rte_cpuflags.o):(.rodata+0x0): multiple definition of `rte_cpu_feature_table'
/opt/dpdk/dpdk-stable-16.11.1/build/lib/librte_eal.a(rte_cpuflags.o):(.rodata+0x0): first defined here
/opt/dpdk/dpdk-stable-16.11.1/build/lib/librte_eal.a(rte_cpuflags.o): In function `rte_cpu_get_flag_name':
rte_cpuflags.c:(.text+0x90): multiple definition of `rte_cpu_get_flag_name'
/opt/dpdk/dpdk-stable-16.11.1/build/lib/librte_eal.a(rte_cpuflags.o):rte_cpuflags.c:(.text+0x90): first defined here
/opt/dpdk/dpdk-stable-16.11.1/build/lib/librte_pmd_virtio.a(virtio_rxtx.o): In function `virtio_rx_offload.part.6':
virtio_rxtx.c:(.text+0xaf): undefined reference to `rte_net_get_ptype'
collect2: error: ld returned 1 exit status
Makefile:43: recipe for target 'Packet++Test' failed
make[1]: *** [Packet++Test] Error 1
make[1]: Leaving directory '/opt/pcapPlus/PcapPlusPlus/Tests/Packet++Test'
Makefile:48: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mmanoj** [comment] 2017-05-01 19:13
Dear @iGeneral & @seladb 

Really appreciate any help on compiling DPDK example.

Thanks in advance.

**Comment by seladb** [comment] 2017-05-02 21:37
I'm working on it, will reproduce this issue and report back

**Comment by mmanoj** [comment] 2017-05-03 18:32
Thanks for the update.Looking forward to resolve the issue.

**Comment by seladb** [comment] 2017-05-03 21:43
Hi, I've done the necessary changes to support DPDK 16.11 and 17.02 and pushed them to master. I compiled PcapPlusPlus with both versions and managed to run the DpdkTrafficFilter example. Could you please pull the code and check?

**Comment by mmanoj** [comment] 2017-05-04 15:55
Hi @seladb 

Thanks a lot for the quick fix. I will test and update you the status.

**Comment by mmanoj** [comment] 2017-05-06 07:08
Hi @seladb ,

I was successfully compiled the library package and examples. Currently I'm testing on DPDK example. Tanks again for quick support provided. I will update about testing progress in my Fedora box.

**Comment by seladb** [comment] 2017-05-08 22:00
Hi @mmanoj , any progress with the testing? Can this issue be marked as resolved?

**Comment by mmanoj** [comment] 2017-05-09 15:39
@seladb 

I need some help to test in VM, as it not clear to me. Meanwhile I'm working on to build physical machine with intel NIC -1 gbps . Still it in progress. Can you guide me to test it in VM, so we can close this issue till physical testing.

**Comment by seladb** [comment] 2017-05-09 15:52
Assuming you have VirtualBox (this is the platform I tested it on): here is a link explaining how to configure it: [http://plvision.eu/deploying-intel-dpdk-in-oracle-virtualbox/](http://plvision.eu/deploying-intel-dpdk-in-oracle-virtualbox/). Please notice this post is rather old so they use an old DPDK version (just replace it with DPDK 17.02 or 16.11)

**Comment by mmanoj** [comment] 2017-05-09 18:39
@seladb 

Thanks for the link,  I done similer with KVM and Fedora Gust and examples working fine, evan L2forwarder. However I run the dpdk example but not sure about the result. I tested as below reference link with packet gen.
http://dannykim.me/danny/openflow/86577?ckattempt=2

**Comment by seladb** [comment] 2017-05-09 19:05
What do you mean by "not sure about the results"? Could you please share the results you're seeing?

**Comment by mmanoj** [comment] 2017-05-09 20:28
root@localhost Bin]# ./DpdkTrafficFilter -d 0 -s 1
EAL: Detected 2 lcore(s)
EAL: Probing VFIO support...
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
EAL: PCI device 0000:00:03.0 on NUMA socket -1
EAL:   probe driver: 8086:100e net_e1000_em
EAL: PCI device 0000:00:08.0 on NUMA socket -1
EAL:   probe driver: 8086:100e net_e1000_em
Using core 1
   Core configuration:
      DPDK device#0: RX-Queue#0;  
^C

Application stopped
Core ID      Packet Count Eth Count    ARP Count    IPv4 Count   IPv6 Count   TCP Count    UDP Count    HTTP Count   Matched TCP Flows Matched UDP Flows Matched Packets   
===========================================================================================================================================================================
1            11           11           0            0            0            0            0            0            0                 0                 11                
Total        11           11           0            0            0            0            0            0            0                 0                 11

**Comment by mmanoj** [comment] 2017-05-09 20:32
I follow the above link and create packet with packetgen, following my host machine config with two virtual cards

enp0s31f6 Link encap:Ethernet  HWaddr 50:7b:9d:68:74:7e  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:16 Memory:e1300000-e1320000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:381625 errors:0 dropped:0 overruns:0 frame:0
          TX packets:381625 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:17893703151 (17.8 GB)  TX bytes:17893703151 (17.8 GB)

virbr0    Link encap:Ethernet  HWaddr fe:54:00:53:ff:b2  
          inet addr:192.168.122.1  Bcast:192.168.122.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:9767 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4793 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:833404 (833.4 KB)  TX bytes:24325405 (24.3 MB)

virbr0-nic Link encap:Ethernet  HWaddr 52:54:00:e5:0f:3b  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

vnet0     Link encap:Ethernet  HWaddr fe:54:00:53:ff:b2  
          inet6 addr: fe80::fc54:ff:fe53:ffb2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:35137267 errors:0 dropped:0 overruns:0 frame:0
          TX packets:23346383 errors:0 dropped:4501 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2112625757 (2.1 GB)  TX bytes:1425146109 (1.4 GB)

vnet1     Link encap:Ethernet  HWaddr fe:54:00:69:c7:f7  
          inet6 addr: fe80::fc54:ff:fe69:c7f7/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:23326991 errors:0 dropped:0 overruns:0 frame:0
          TX packets:35135720 errors:0 dropped:4493 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1399890234 (1.3 GB)  TX bytes:2112406374 (2.1 GB)

wlp1s0    Link encap:Ethernet  HWaddr e0:94:67:47:63:f5  
          inet addr:192.168.1.106  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::e01:6c63:6d93:f3b2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:552782 errors:0 dropped:0 overruns:0 frame:0
          TX packets:239760 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:691360053 (691.3 MB)  TX bytes:38340764 (38.3 MB)
============
vnet0 & vnet1 my virtual network card use in KVM.

**Comment by mmanoj** [comment] 2017-05-09 20:33
[root@localhost Bin]# ./DpdkTrafficFilter -l
EAL: Detected 2 lcore(s)
EAL: Probing VFIO support...
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
EAL: PCI device 0000:00:03.0 on NUMA socket -1
EAL:   probe driver: 8086:100e net_e1000_em
EAL: PCI device 0000:00:08.0 on NUMA socket -1
EAL:   probe driver: 8086:100e net_e1000_em
DPDK port list:
    Port #0: MAC address='52:54:00:53:ff:b2'; PCI address='0000:00:03.0'; PMD='net_e1000_em'
    Port #1: MAC address='52:54:00:69:c7:f7'; PCI address='0000:00:08.0'; PMD='net_e1000_em'

**Comment by seladb** [comment] 2017-05-09 21:09
It seems like the DPDK example is working fine. In the output you posted the application captured 11 packets, all are Ethernet packets but they're probably ARP packets because IPv4, IPv6, TCP, UDP and HTTP counts are 0.
But it seems the example is really working like it should

**Comment by mmanoj** [comment] 2017-05-10 09:54
How to test HTTP traffic over virtual box ? or KVM. Can you provide me some guide.

**Comment by seladb** [comment] 2017-05-10 18:44
I did the following (using VirtualBox): created an Ubuntu guest and configured two similar network adapters as "Bridge Adapter" and as "Intel PRO/1000 MT Desktop (82540EM)". Inside this guest I built DPDK and PcapPlusPlus. Then I ran setup-dpdk for only one of the interfaces: _./setup-dpdk.sh -p 256 -n eth1_ 
I ran the PcapPlusPlus DPDK example and in parallel I surfed the web using a web browser (all on the guest machine). The Internet traffic went through the non-DPDK interface (eth0 in my case) but the traffic is also captured on the DPDK interface (eth1 in my case) since both of the virtual interfaces are actually connected to the real NIC (the one on the host).
Hope this helps

**Comment by mmanoj** [comment] 2017-05-10 19:43
Hi @seladb ,

Thank for the suggestion, it's make sense, I also forwarding traffic to second nic (port1). I will test and update you the result. In my case I have fedora gust and KVM

**Comment by mmanoj** [comment] 2017-05-14 18:07
Hi @seladb 

/DpdkTrafficFilter  -d 0

I tried, but result as follows, no HTTP paclets.

Application stopped
Core ID      Packet Count Eth Count    ARP Count    IPv4 Count   IPv6 Count   TCP Count    UDP Count    HTTP Count   Matched TCP Flows Matched UDP Flows Matched Packets   
===========================================================================================================================================================================
1            31           31           0            0            0            0            0            0            0                 0                 31                
Total        31           31           0            0            0            0            0            0            0                 0                 31

**Comment by mmanoj** [comment] 2017-05-14 18:09
I done follwing before bind, as it not allow me to bind without below steps:

ifconfig ens3 down
ip addr flush dev ens3

**Comment by seladb** [comment] 2017-05-15 09:18
I didn't try KVM, only VirtualBox. Can you please try with VirtualBox?

**Comment by mmanoj** [comment] 2017-05-15 10:04
Hi @seladb 

I will setup virtual box env and update you the result, I'm still waiting my NIC to arrive, so I will have physical box to test.

**Comment by seladb** [comment] 2017-05-15 11:01
Ok thanks, in the meantime please test it with VirtualBox so I'll be able to close the ticket

**Comment by mmanoj** [comment] 2017-05-15 14:07
I'm working on it, will update you soon.

**Comment by mmanoj** [comment] 2017-05-15 16:54
Hi @seladb 

I able to setup virtual box and tested as per your guidelines, still show HTTP count as 0. Any idea ?

**Comment by seladb** [comment] 2017-05-15 19:45
Did you manage to see any UDP/TCP packets? You can capture packets on the other interface and see if there are packets that are captured there and not captured on the DPDK device

**Comment by mmanoj** [comment] 2017-05-15 20:02
Hi,

I bind only one interface to DPDK (port 0) and other interface is bridge to physical NIC. Yes I saw some UDP/TCP packets as previous result.I want to capture some HTTP traffic. look like virtual interface bit complex to test. Any suggestion I can try.

**Comment by seladb** [comment] 2017-05-15 20:13
If you followed my suggestion you should have 2 interfaces binded to the same physical NIC so both should see the same traffic. One should be binded to DPDK and the other should not. If this is the case - do you see HTTP packets on the NIC not binded to DPDK?

**Comment by mmanoj** [comment] 2017-05-16 20:09
Hi,

I follow the same instructions and I browse the net via second bridge virtual interface.  Did you mean check the packets using tcpdump for not binded interface ?

**Comment by seladb** [comment] 2017-05-16 20:21
Yes. You can use tcpdump or Wireshark (tshark). The purpose is to make sure you see HTTP packets on the non binded interface

**Comment by mmanoj** [comment] 2017-05-17 07:50
Hi,

I will update after test, I got NIC card, working to setup physical ENV too. So we can test both. I will update the result soon. Following is good ref:
http://dannykim.me/danny/openflow/86577?ckattempt=2

Note: I'm documenting all steps. So it will helpful in the future for all. Will share once finish.

**Comment by mmanoj** [comment] 2017-05-19 19:00
Hi @seladb 

I setup the physical card with my physical box and binging success with DPDK UIO driver and it's list under DPDK ports, and I connect port 1 to my laptop using cross network cable and try to get the network connection (like bump in the wire) but it's not connect or get IP address to my laptop. Following is my connection scenario.

home INTERNET router --> DPDK card port 0 --> DPDK forwarding App--> DPDK port 1 --> Laptop via cross cable

Can you please advice on this. What I try to do forward network connection back and forth via DPDK to INTERNET and Laptop.

Seeking your advice.

**Comment by seladb** [comment] 2017-05-21 12:17
I'm not sure as I haven't tried DPDK forwarding app. Are you using the L2 forwarding app? Maybe you can google it...

**Comment by mmanoj** [comment] 2017-05-21 15:28
Hi @seladb 

I'm using PcapPlusPlus DPDK example as forwarder. I tried L2 app also, not much success. I'm still testing. If you can advice based on your DPDK example, it will help.

**Comment by seladb** [comment] 2017-05-21 18:17
I suggest you first try to activate the DPDK example. If it works then move to PcapPlusPlus DPDK example

**Comment by mmanoj** [comment] 2017-05-21 19:05
Hi @seladb ;

I'm trying with L2forwarding example with below senario:

home INTERNET router --> DPDK card port 0 --> DPDK forwarding App--> DPDK port 1 --> Laptop via cross cable

I'm try to ping, no success, after that I add arp entry as below in my laptop mentioning my gateway at DPDK port 1. after that ping sending packets but not receiving. I'm trying to forward browsing traffic from laptop via DPDK l2forwarder to internet and back.

Your advice to resolve this great help.

**Comment by mmanoj** [comment] 2017-05-21 19:15
@seladb 

Following link having some hint, your feedback highly appreciated.
http://dpdk.org/ml/archives/dev/2013-June/000237.html

**Comment by mmanoj** [comment] 2017-05-28 08:51
Hi @seladb 

Please confirm below, is your DPDK example working only one way as forwarder, not replay back to client.

If it's the case, what is the way forward to make bi-directional forwarding, like edge router. Your advice highly appreciated.

**Comment by seladb** [comment] 2017-05-28 10:50
Hi, I didn't write this example as a forwarder but rather as a packet inspection application. You can try to convert it into a forwarder if you'd like, but it'll probably take some work

**Comment by mmanoj** [comment] 2017-05-28 19:20
@seladb 

Thanks for the feedback, I'm still not clear about bi-directional forwarding (request/replay)  for web traffic with L3 forwarder. Once I clear, I will start implementation. If you can guide me I'm really appreciated.

Thank you,
Manoj M

**Comment by inbrahimnasson** [comment] 2017-05-28 19:23
Hey i thing you got the wrong email am not seladb though i was also in the
forum ,so please get the right seladb mail

**Comment by mmanoj** [comment] 2017-05-28 19:35
@inbrahimnasson 

Sorry, hope your in same thread, may be that's why u got the notification.

**Comment by inbrahimnasson** [comment] 2017-05-28 19:44
yaaah sure maybe

**Comment by mmanoj** [comment] 2017-05-31 20:15
Hi @seladb 

I tested with basic DPDK forwarding example, and It's able to send / receive packet via INTERNET. Either L2 or PcapPlusPlus DPDK example not work as same. This is the update as of today. Any advice welcome to make PcapPlusPlus DPDK example to make as same.

**Comment by seladb** [comment] 2017-06-13 05:36
Closing this issue for now, if you still encounter problems please reopen it

**Closed by seladb** 2017-06-13 05:36 UTC

**Comment by mmanoj** [comment] 2017-06-14 18:52
@seladb 

Just to update, I was success with DPDK skeleton app, I need to convert it with your app. I will update once completed, Thanks again for great support provided. Keep in touch.
