### ISSUE TITLE
Dump when call getFieldByName with http response.

### ISSUE THREAD

**Issue by ugenehan** [seladb/PcapPlusPlus#307] opened 2019-11-22 08:22 UTC
When deal a http response package to get it's filed like user-agent,but there is no this filed,at this time,the app dumped.
line 381 in file TextBasedProtocol.cpp

**Comment by seladb** [comment] 2019-11-22 21:39
I'm not sure I can reproduce this issue. If you're trying to retrieve a field that doesn't exist `TextBasedProtocolMessage::getFieldByName()` will return NULL, so you have to check the return value for NULLs.

In case I misunderstand the issue, it'd be helpful if you can add a code snippet that reproduces the problem.

**Comment by ugenehan** [comment] 2019-11-23 03:13
> I'm not sure I can reproduce this issue. If you're trying to retrieve a field that doesn't exist `TextBasedProtocolMessage::getFieldByName()` will return NULL, so you have to check the return value for NULLs.
> 
> In case I misunderstand the issue, it'd be helpful if you can add a code snippet that reproduces the problem.

When I analyze an http response package, I call the func getFieldByName with parameter “PCPP_HTTP_USER_AGENT_FIELD”(in fact the http response has no this filed)，the program dumped. So I debug the dump file with gdb,it display the error caused by line 381 of the TextBasedProtocol.cpp file,and the dump code is "range = m_FieldNameToFieldMap.equal_range(fieldName);"

I use the example "HttpAnalyzer" with the func 'CollectStats',add the flowing code:

    pcpp::HttpRequestLayer *req = httpPacket->getLayerOfType<pcpp::HttpRequestLayer>();
    pcpp::HeaderField *headerField = req->getFieldByName(PCPP_HTTP_USER_AGENT_FIELD); // dump at this line
    if(headerField != NULL){
            ...........
            return;
        }
    }

**Comment by seladb** [comment] 2019-11-23 03:49
I ran the same code but it didn't crash. Can you provide a pcap file with the packet that causes the crash?

**Comment by ugenehan** [comment] 2019-11-23 04:35
> I ran the same code but it didn't crash. Can you provide a pcap file with the packet that reproduces the crash?

OK. 
[http.zip](https://github.com/seladb/PcapPlusPlus/files/3882140/http.zip)

**Comment by seladb** [comment] 2019-11-23 19:14
Thank you, I'll take a look and fix the bug

**Comment by seladb** [comment] 2019-11-24 01:42
I tried to run the same code but I don't get a failure. In your code, do you check that `req != NULL`?

```cpp
pcpp::HttpRequestLayer *req = httpPacket->getLayerOfType<pcpp::HttpRequestLayer>();
if (req != NULL) {
    pcpp::HeaderField *headerField = req->getFieldByName(PCPP_HTTP_USER_AGENT_FIELD); // dump at this line
    if(headerField != NULL){
        ...........
        return;
     }
}
```

**Comment by ugenehan** [comment] 2019-11-25 02:12
> * t

1.My OS is centos 7.5.1804,'Linux mail.narixt.com 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux'
2.I use the HttpAnalyzer example,add the above code to the function collectStats() ,and my port is 31600

**Comment by seladb** [comment] 2019-11-25 07:56
Thanks. Did you try the check I wrote before `req != NULL`?

**Comment by seladb** [comment] 2019-12-05 00:00
Since I didn't hear back from you I'm assuming you solved it, so I'll close the issue now. Please reopen if needed

**Closed by seladb** 2019-12-05 00:00 UTC
