### ISSUE TITLE
crash in PcapLiveDeviceList::getPcapLiveDeviceByIp(IPv4Address ipAddr)

### ISSUE THREAD

**Issue by inbrahimnasson** [seladb/PcapPlusPlus#147] opened 2018-11-18 08:02 UTC
when use PcapLiveDeviceList::getInstance().getPcapLiveDeviceByIp("192.168.139.131")
the program crashes due to the nullptr passed in function sockaddr2in_addr(addrIter->addr)
within the PcapLiveDeviceList::getPcapLiveDeviceByIp(IPv4Address ipAddr)

please look to it it has be there for a long time thought in the new release the bug would have been solve!!

**Comment by inbrahimnasson** [comment] 2018-11-18 16:19
Hints:This happens in linux but for windows is okay

**Comment by seladb** [comment] 2018-11-21 18:53
I'm sorry for the delayed response, I'll look into it and keep you posted

**Comment by seladb** [comment] 2018-11-21 23:12
I'm not able to reproduce this issue. In my Linux system `addrIter->addr` is probably never null and I don't know how to make it null. These pointers come from libpcap and I'm not sure how it populates them.

Do you have any special configurations or network interfaces in your system that might cause `addrIter->addr` to be null?

**Comment by inbrahimnasson** [comment] 2018-11-29 06:06
it tested it in some other Centos 7 of other machines seems to work very fine, i haven't figure it out the root of the problem but i still on it as soon as i get the root of problem i will let you know

**Comment by seladb** [comment] 2018-12-06 01:55
sure, let me close this issue for now. Please feel free reopen it if you manage to find the root cause

**Closed by seladb** 2018-12-06 01:55 UTC

**Comment by ibrahimnasson** [comment] 2019-03-30 11:33
#170 solved the issue
