### ISSUE TITLE
startCaptureBlockingMode gives segfault when running in loop

### ISSUE THREAD

**Issue by Arijit-hydrated** [seladb/PcapPlusPlus#172] opened 2019-03-30 17:19 UTC
Hi,

While using startCaptureBlockingMode in a while loop, it works only for the first iteration and gives segfault for all the next iterations. Please look into this. 

Code snippet attached below:

while (num < num_packets) {

		captured = 0;
		
		pcpp::Packet pkt = createPacket(key_seq[num], val_seq[num], rw_seq[num]);
		if (!dev->sendPacket(&pkt))
		{
			fprintf(stderr, "Couldn't send packet\n");
			exit(1);
		}

		fprintf(stderr, "Packet sent!\n");
		printf("\nStarting capture in blocking mode...\n");
	
		captured = dev->startCaptureBlockingMode(onPacketArrivesBlockingMode, &stats, timeout);

		if (captured == 1) {
			fprintf(stderr, "Packet rcvd\n");

		stats.printToConsole();

		}

		num += 1;
		
	}

**Comment by seladb** [comment] 2019-04-06 08:06
Can you please run this with `gdb` and print the stack trace you get?

**Comment by seladb** [comment] 2019-04-23 01:31
I could not reproduce this segfault. Can you please give more instructions on how to reproduce it or run it with `gdb` and print the stack trace?

**Comment by seladb** [comment] 2019-04-29 19:13
I'll close this issue now since I didn't see any response for a long time. Please reopen it as needed

**Closed by seladb** 2019-04-29 19:13 UTC
Labels: non-reproducable

**Comment by gerald-dotcom** [comment] 2020-10-17 15:51
Found this while fiddling around. I can confirm I hit the same bug.

**Comment by seladb** [comment] 2020-10-17 17:57
@gerald-dotcom can you guide me how to reproduce it?

**Comment by gerald-dotcom** [comment] 2020-10-17 17:58
> @gerald-dotcom can you guide me how to reproduce it?

I fixed it and closed the issue. I was not checking whether Ethernet layer null or not
