### ISSUE TITLE
Mac os couldn't work

### ISSUE THREAD

**Issue by BeiluobluesNing** [seladb/PcapPlusPlus#211] opened 2019-07-11 12:43 UTC
I've follow the tutorial about [download and building](https://seladb.github.io/PcapPlusPlus-Doc/download.html), and past all the unit test:

> PcapPlusPlus version: v19.04+ (non-official release)
Built: Jul 11 2019 20:02:30
Built from: Git branch 'master', commit 'fe2d92c3f5f3b171758cc096870b95961aeeac1c'
Starting tests...
> 
> EthPacketCreation             : PASSED
> EthPacketPointerCreation      : PASSED
> EthAndArpPacketParsing        : PASSED
> ArpPacketCreation             : PASSED
> VlanParseAndCreation          : PASSED
> Ipv4PacketCreation            : PASSED
> Ipv4PacketParsing             : PASSED
> Ipv4FragmentationTest         : PASSED
> Ipv4OptionsParsingTest        : PASSED
> Ipv4OptionsEditTest           : PASSED
> Ipv4UdpChecksum               : PASSED
> Ipv6UdpPacketParseAndCreate   : PASSED
> Ipv6FragmentationTest         : PASSED
> Ipv6ExtensionsTest            : PASSED
> TcpPacketNoOptionsParsing     : PASSED
> TcpPacketWithOptionsParsing   : PASSED
> TcpPacketWithOptionsParsing2  : PASSED
> TcpPacketCreation             : PASSED
> TcpPacketCreation2            : PASSED
> InsertDataToPacket            : PASSED
> InsertVlanToPacket            : PASSED
> RemoveLayerTest               : PASSED
> HttpRequestLayerParsingTest   : PASSED
> HttpRequestLayerCreationTest  : PASSED
> HttpRequestLayerEditTest      : PASSED
> HttpResponseLayerParsingTest  : PASSED
> HttpResponseLayerCreationTest : PASSED
> HttpResponseLayerEditTest     : PASSED
> PPPoESessionLayerParsingTest  : PASSED
> PPPoESessionLayerCreationTest : PASSED
> PPPoEDiscoveryLayerParsingTest: PASSED
> PPPoEDiscoveryLayerCreateTest : PASSED
> DnsLayerParsingTest           : PASSED
> DnsLayerQueryCreationTest     : PASSED
> DnsLayerResourceCreationTest  : PASSED
> DnsLayerEditTest              : PASSED
> DnsLayerRemoveResourceTest    : PASSED
> MplsLayerTest                 : PASSED
> CopyLayerAndPacketTest        : PASSED
> IcmpParsingTest               : PASSED
> IcmpCreationTest              : PASSED
> IcmpEditTest                  : PASSED
> GreParsingTest                : PASSED
> GreCreationTest               : PASSED
> GreEditTest                   : PASSED
> SSLClientHelloParsingTest     : PASSED
> SSLAppDataParsingTest         : PASSED
> SSLAlertParsingTest           : PASSED
> SSLMultipleRecordParsingTest  : PASSED
> SSLMultipleRecordParsing2Test : PASSED
> SSLMultipleRecordParsing3Test : PASSED
> SSLMultipleRecordParsing4Test : PASSED
> SSLPartialCertificateParseTest: PASSED
> SSLNewSessionTicketParseTest  : PASSED
> SllPacketParsingTest          : PASSED
> SllPacketCreationTest         : PASSED
> DhcpParsingTest               : PASSED
> DhcpCreationTest              : PASSED
> DhcpEditTest                  : PASSED
> NullLoopbackTest              : PASSED
> IgmpParsingTest               : PASSED
> IgmpCreateAndEditTest         : PASSED
> Igmpv3ParsingTest             : PASSED
> Igmpv3QueryCreateAndEditTest  : PASSED
> Igmpv3ReportCreateAndEditTest : PASSED
> ParsePartialPacketTest        : PASSED
> VxlanParsingAndCreationTest   : PASSED
> SipRequestLayerParsingTest    : PASSED
> SipRequestLayerCreationTest   : PASSED
> SipRequestLayerEditTest       : PASSED
> SipResponseLayerParsingTest   : PASSED
> SipResponseLayerCreationTest  : PASSED
> SipResponseLayerEditTest      : PASSED
> SdpLayerParsingTest           : PASSED
> SdpLayerCreationTest          : PASSED
> SdpLayerEditTest              : PASSED
> PacketTrailerTest             : PASSED
> RadiusLayerParsingTest        : PASSED
> RadiusLayerCreationTest       : PASSED
> RadiusLayerEditTest           : PASSED
> ALL TESTS PASSED!!
> 

> Git info: Git branch 'master', commit 'fe2d92c3f5f3b171758cc096870b95961aeeac1c'
> Using ip: 10.0.0.1
> Debug mode: off
> Starting tests...
> TestIPAddress                 : PASSED
> TestMacAddress                : PASSED
> TestPcapFileReadWrite         : PASSED
> TestPcapSllFileReadWrite      : PASSED
> TestPcapRawIPFileReadWrite    : PASSED
> TestPcapFileAppend            : PASSED
> TestPcapNgFileReadWrite       : PASSED
> TestPcapNgFileReadWriteAdv    : PASSED
> TestPcapLiveDeviceList        : PASSED
> TestPcapLiveDeviceListSearch  : FAILED. assertion failed: Device used in this test 10.0.0.1 doesn't exist
> TestPcapLiveDevice            : FAILED. assertion failed: Device used in this test 10.0.0.1 doesn't exist
> TestPcapLiveDeviceNoNetworking: PASSED
> TestPcapLiveDeviceStatsMode   : FAILED. assertion failed: Device used in this test 10.0.0.1 doesn't exist
> TestPcapLiveDeviceBlockingMode: FAILED. assertion failed: Step 0: Device used in this test 10.0.0.1 doesn't exist
> TestPcapLiveDeviceSpecialCfg  : FAILED. assertion failed: Step 0: Device used in this test 10.0.0.1 doesn't exist
> Segmentation fault: 11

And I think I don't have a device so i haven't pass the last one.
When I try to run the[ Sample code  ](https://github.com/seladb/PcapPlusPlus)
`g++ -Iinclude -c handle_pcap.cpp --std=c++11`
what I get is that:
`handle_pcap.cpp:9:10: fatal error: 'PcapFileDevice.h' file not found
#include "PcapFileDevice.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated. `
How could I figure out this thing?

**Comment by seladb** [comment] 2019-07-11 17:27
Did you run `sudo make install`?

**Comment by BeiluobluesNing** [comment] 2019-07-12 03:24
Actually I have follow all the steps and get this infomation...
> MacBook-Pro:PcapPlusPlus ningpeirong$ sudo make install
> Password:
> Installation complete!

And still...

> handle_pcap.cpp:9:10: fatal error: 'PcapFileDevice.h' file not found
> #include "PcapFileDevice.h"
>          ^~~~~~~~~~~~~~~~~~
> 1 error generated.

**Comment by seladb** [comment] 2019-07-12 05:27
Could you please share your code?
It seems that somehow the compiler cannot find the header files. Could you please check under `/usr/local/include/pcapplusplus` and let me know if you see PcapPlusPlus header files there?

**Comment by BeiluobluesNing** [comment] 2019-07-12 05:47
[code](https://pastebin.com/YQytTR2x)
And` /usr/local/include/pcapplusplus`

>  `MacBook-Pro:test_pcap ningpeirong$ cd /usr/local/include/pcapplusplus
> MacBook-Pro:pcapplusplus ningpeirong$ ls

> ArpLayer.h			LRUList.h			PfRingDeviceList.h
> Device.h			Layer.h				PlatformSpecificUtils.h
> DhcpLayer.h			LinuxNicInformationSocket.h	PointerVector.h
> DnsLayer.h			Logger.h			ProtocolType.h
> DnsLayerEnums.h			MBufRawPacket.h			RadiusLayer.h
> DnsResource.h			MacAddress.h			RawPacket.h
> DnsResourceData.h		MplsLayer.h			RawSocketDevice.h
> DpdkDevice.h			NetworkUtils.h			SSLCommon.h
> DpdkDeviceList.h		NullLoopbackLayer.h		SSLHandshake.h
> EthLayer.h			PPPoELayer.h			SSLLayer.h
> GeneralUtils.h			Packet.h			SdpLayer.h
> GreLayer.h			PacketTrailerLayer.h		SipLayer.h
> HttpLayer.h			PacketUtils.h			SllLayer.h
> IPReassembly.h			PayloadLayer.h			SystemUtils.h
> IPv4Layer.h			PcapDevice.h			TLVData.h
> IPv6Extensions.h		PcapFileDevice.h		TablePrinter.h
> IPv6Layer.h			PcapFilter.h			TcpLayer.h
> IcmpLayer.h			PcapLiveDevice.h		TcpReassembly.h
> IgmpLayer.h			PcapLiveDeviceList.h		TextBasedProtocol.h
> IpAddress.h			PcapPlusPlusVersion.h		UdpLayer.h
> IpUtils.h			PcapRemoteDevice.h		VlanLayer.h
> KniDevice.h			PcapRemoteDeviceList.h		VxlanLayer.h
> KniDeviceList.h			PfRingDevice.h			WinPcapLiveDevice.h`

**Comment by seladb** [comment] 2019-07-12 05:58
do you use MacOS 10.14 Mojave?

If yes, did run the extra step: 

`sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /`

**Comment by BeiluobluesNing** [comment] 2019-07-12 06:07
Yeah, it's  MacOS 10.14 Mojave, and I have followed the step but it still ...

> MacBook-Pro:PcapPlusPlus user$ sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
> Password:
> installer: Package name is macOS_SDK_headers_for_macOS_10.14
> installer: Upgrading at base path /
> installer: The upgrade was successful.

> MacBook-Pro:test_pcap user$ g++ -Iinclude -c handle_pcap.cpp --std=c++11
> handle_pcap.cpp:9:10: fatal error: 'PcapFileDevice.h' file not found
> #include "PcapFileDevice.h"
>          ^~~~~~~~~~~~~~~~~~
> 1 error generated.

Might be I should use Ubuntu rather than Mac os :P

**Comment by seladb** [comment] 2019-07-12 06:22
This should work on MacOS as well... for some reason the compiler (`g++`) can't find the header files under `/usr/local/include/pcapplusplus` and I'm not sure why. Maybe you can try to implicitly add `-I/usr/local/include/pcapplusplus` to your makefile and see if that works?

**Comment by BeiluobluesNing** [comment] 2019-07-12 06:27
It work, but there's new problem...

> handle_pcap.cpp:38:48: error: no matching member function for call to 'getLayerOfType'
>         pcpp::IPv4Address srcIP = parsedPacket.getLayerOfType()->getSrcIpAddress();
>                                   ~~~~~~~~~~~~~^~~~~~~~~~~~~~
> /usr/local/include/pcapplusplus/Packet.h:309:18: note: candidate template ignored: couldn't infer template argument
>       'TLayer'
>         TLayer* Packet::getLayerOfType()
>                         ^
> /usr/local/include/pcapplusplus/Packet.h:243:10: note: candidate function not viable: requires at least argument
>       'layerType', but no arguments were provided
>                 Layer* getLayerOfType(ProtocolType layerType, int index = 0);
>                        ^
> handle_pcap.cpp:39:49: error: no matching member function for call to 'getLayerOfType'
>         pcpp::IPv4Address destIP = parsedPacket.getLayerOfType()->getDstIpAddress();
>                                    ~~~~~~~~~~~~~^~~~~~~~~~~~~~
> /usr/local/include/pcapplusplus/Packet.h:309:18: note: candidate template ignored: couldn't infer template argument
>       'TLayer'
>         TLayer* Packet::getLayerOfType()
>                         ^
> /usr/local/include/pcapplusplus/Packet.h:243:10: note: candidate function not viable: requires at least argument
>       'layerType', but no arguments were provided
>                 Layer* getLayerOfType(ProtocolType layerType, int index = 0);
>                        ^
> 2 errors generated.

**Comment by seladb** [comment] 2019-07-12 06:34
The issue is this: `getLayerOfType()` is a templated method, you should use it like this:

```cpp
pcpp::IPv4Address destIP = parsedPacket.getLayerOfType<pcpp::IPv4Layer>()->getDstIpAddress();
```

**Comment by BeiluobluesNing** [comment] 2019-07-12 06:51
fix line 38 and 39 to 
` pcpp::IPv4Address srcIP = parsedPacket.getLayerOfType<pcpp::IPv4Layer>()->getSrcIpAddress();
        pcpp::IPv4Address destIP = parsedPacket.getLayerOfType<pcpp::IPv4Layer>()>getDstIpAddress();`

And another prob.....

> Undefined symbols for architecture x86_64:
  "pcpp::IFileDevice::close()", referenced from:
      _main in handle_pcap-08f500.o
  "pcpp::IFileDevice::~IFileDevice()", referenced from:
      pcpp::IFileReaderDevice::~IFileReaderDevice() in handle_pcap-08f500.o
  "pcpp::IPv4Address::IPv4Address(unsigned int)", referenced from:
      pcpp::IPv4Layer::getSrcIpAddress() in handle_pcap-08f500.o
      pcpp::IPv4Layer::getDstIpAddress() in handle_pcap-08f500.o
  "pcpp::IPv4Address::~IPv4Address()", referenced from:
      _main in handle_pcap-08f500.o
  "pcpp::PcapFileReaderDevice::getNextPacket(pcpp::RawPacket&)", referenced from:
      _main in handle_pcap-08f500.o
  "pcpp::PcapFileReaderDevice::open()", referenced from:
      _main in handle_pcap-08f500.o
  "pcpp::PcapFileReaderDevice::PcapFileReaderDevice(char const*)", referenced from:
      _main in handle_pcap-08f500.o
  "pcpp::Packet::Packet(pcpp::RawPacket*, bool, pcpp::ProtocolType, pcpp::OsiModelLayer)", referenced from:
      _main in handle_pcap-08f500.o
  "pcpp::Packet::~Packet()", referenced from:
      _main in handle_pcap-08f500.o
  "pcpp::RawPacket::RawPacket()", referenced from:
      _main in handle_pcap-08f500.o
  "pcpp::RawPacket::~RawPacket()", referenced from:
      _main in handle_pcap-08f500.o
  "typeinfo for pcpp::Layer", referenced from:
      pcpp::IPv4Layer* pcpp::Packet::getLayerOfType<pcpp::IPv4Layer>() in handle_pcap-08f500.o
      pcpp::IPv4Layer* pcpp::Packet::getNextLayerOfType<pcpp::IPv4Layer>(pcpp::Layer*) in handle_pcap-08f500.o
  "typeinfo for pcpp::IPv4Layer", referenced from:
      pcpp::IPv4Layer* pcpp::Packet::getLayerOfType<pcpp::IPv4Layer>() in handle_pcap-08f500.o
      pcpp::IPv4Layer* pcpp::Packet::getNextLayerOfType<pcpp::IPv4Layer>(pcpp::Layer*) in handle_pcap-08f500.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

And I've google this prob but still have no clue...

I have no idea about  your time zone, and if it's too late might be you could take a sleep..

**Comment by seladb** [comment] 2019-07-12 07:12
These errors are very weird, I've never seen them before... I googled it and found the following pages:

https://stackoverflow.com/questions/55134327/osx-mojave-ld-symbols-not-found-for-architecture-x86-64-clang-error-linke

https://stackoverflow.com/questions/10156582/clang-iostream-symbol-not-found

Maybe you should try to add the `-lstdc++` flag?

**Comment by BeiluobluesNing** [comment] 2019-07-12 07:26
I also try to google it and these solution might not suit for me...
`clang -x c++ -I/usr/local/include/pcapplusplus handle_pcap.cpp`
and 
`g++ -I/usr/local/include/pcapplusplus handle_pcap.cpp --std=c++11 -lstdc++`
both of them output is:

> Undefined symbols for architecture x86_64:
  "pcpp::IFileDevice::close()", referenced from:
      _main in handle_pcap-135c73.o
  "pcpp::IFileDevice::~IFileDevice()", referenced from:
      pcpp::IFileReaderDevice::~IFileReaderDevice() in handle_pcap-135c73.o
  "pcpp::IPv4Address::IPv4Address(unsigned int)", referenced from:
      pcpp::IPv4Layer::getSrcIpAddress() in handle_pcap-135c73.o
      pcpp::IPv4Layer::getDstIpAddress() in handle_pcap-135c73.o
  "pcpp::IPv4Address::~IPv4Address()", referenced from:
      _main in handle_pcap-135c73.o
  "pcpp::PcapFileReaderDevice::getNextPacket(pcpp::RawPacket&)", referenced from:
      _main in handle_pcap-135c73.o
  "pcpp::PcapFileReaderDevice::open()", referenced from:
      _main in handle_pcap-135c73.o
  "pcpp::PcapFileReaderDevice::PcapFileReaderDevice(char const*)", referenced from:
      _main in handle_pcap-135c73.o
  "pcpp::Packet::Packet(pcpp::RawPacket*, bool, pcpp::ProtocolType, pcpp::OsiModelLayer)", referenced from:
      _main in handle_pcap-135c73.o
  "pcpp::Packet::~Packet()", referenced from:
      _main in handle_pcap-135c73.o
  "pcpp::RawPacket::RawPacket()", referenced from:
      _main in handle_pcap-135c73.o
  "pcpp::RawPacket::~RawPacket()", referenced from:
      _main in handle_pcap-135c73.o
  "typeinfo for pcpp::Layer", referenced from:
      pcpp::IPv4Layer* pcpp::Packet::getLayerOfType<pcpp::IPv4Layer>() in handle_pcap-135c73.o
      pcpp::IPv4Layer* pcpp::Packet::getNextLayerOfType<pcpp::IPv4Layer>(pcpp::Layer*) in handle_pcap-135c73.o
  "typeinfo for pcpp::IPv4Layer", referenced from:
      pcpp::IPv4Layer* pcpp::Packet::getLayerOfType<pcpp::IPv4Layer>() in handle_pcap-135c73.o
      pcpp::IPv4Layer* pcpp::Packet::getNextLayerOfType<pcpp::IPv4Layer>(pcpp::Layer*) in handle_pcap-135c73.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

`clang++ -I/usr/local/include/pcapplusplus handle_pcap.cpp --std=c++11 -lstdc++`
and output

> Undefined symbols for architecture x86_64:
  "pcpp::IFileDevice::close()", referenced from:
      _main in handle_pcap-683dbb.o
  "pcpp::IFileDevice::~IFileDevice()", referenced from:
      pcpp::IFileReaderDevice::~IFileReaderDevice() in handle_pcap-683dbb.o
  "pcpp::IPv4Address::IPv4Address(unsigned int)", referenced from:
      pcpp::IPv4Layer::getSrcIpAddress() in handle_pcap-683dbb.o
      pcpp::IPv4Layer::getDstIpAddress() in handle_pcap-683dbb.o
  "pcpp::IPv4Address::~IPv4Address()", referenced from:
      _main in handle_pcap-683dbb.o
  "pcpp::PcapFileReaderDevice::getNextPacket(pcpp::RawPacket&)", referenced from:
      _main in handle_pcap-683dbb.o
  "pcpp::PcapFileReaderDevice::open()", referenced from:
      _main in handle_pcap-683dbb.o
  "pcpp::PcapFileReaderDevice::PcapFileReaderDevice(char const*)", referenced from:
      _main in handle_pcap-683dbb.o
  "pcpp::Packet::Packet(pcpp::RawPacket*, bool, pcpp::ProtocolType, pcpp::OsiModelLayer)", referenced from:
      _main in handle_pcap-683dbb.o
  "pcpp::Packet::~Packet()", referenced from:
      _main in handle_pcap-683dbb.o
  "pcpp::RawPacket::RawPacket()", referenced from:
      _main in handle_pcap-683dbb.o
  "pcpp::RawPacket::~RawPacket()", referenced from:
      _main in handle_pcap-683dbb.o
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init(char const*, unsigned long)", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string<std::__1::nullptr_t>(char const*) in handle_pcap-683dbb.o
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()", referenced from:
      _main in handle_pcap-683dbb.o
  "std::terminate()", referenced from:
      ___clang_call_terminate in handle_pcap-683dbb.o
  "typeinfo for pcpp::Layer", referenced from:
      pcpp::IPv4Layer* pcpp::Packet::getLayerOfType<pcpp::IPv4Layer>() in handle_pcap-683dbb.o
      pcpp::IPv4Layer* pcpp::Packet::getNextLayerOfType<pcpp::IPv4Layer>(pcpp::Layer*) in handle_pcap-683dbb.o
  "typeinfo for pcpp::IPv4Layer", referenced from:
      pcpp::IPv4Layer* pcpp::Packet::getLayerOfType<pcpp::IPv4Layer>() in handle_pcap-683dbb.o
      pcpp::IPv4Layer* pcpp::Packet::getNextLayerOfType<pcpp::IPv4Layer>(pcpp::Layer*) in handle_pcap-683dbb.o
  "___cxa_begin_catch", referenced from:
      ___clang_call_terminate in handle_pcap-683dbb.o
  "___dynamic_cast", referenced from:
      pcpp::IPv4Layer* pcpp::Packet::getLayerOfType<pcpp::IPv4Layer>() in handle_pcap-683dbb.o
      pcpp::IPv4Layer* pcpp::Packet::getNextLayerOfType<pcpp::IPv4Layer>(pcpp::Layer*) in handle_pcap-683dbb.o
  "___gxx_personality_v0", referenced from:
      _main in handle_pcap-683dbb.o
      Dwarf Exception Unwind Info (__eh_frame) in handle_pcap-683dbb.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

If your test haven't this problem, it might be it's my own environmental issue... Thanks for your time

**Comment by seladb** [comment] 2019-07-12 07:48
I'm sorry none of these work. 
One more try: did you manage to compile PcapPlusPlus itself? The reason I'm asking is because all of the [examples](https://github.com/seladb/PcapPlusPlus/tree/master/Examples) are also built as part of the build process so maybe you can take the makefile from there

**Comment by BeiluobluesNing** [comment] 2019-07-12 08:06
If you mean[ Building PcapPlusPlus - MacOS](https://seladb.github.io/PcapPlusPlus-Doc/download.html)..?
All of these  haven't got any prob...

**Comment by seladb** [comment] 2019-07-12 08:17
ok, so that mean PcapPlusPlus examples got built somehow. You can try and take the Makefile from one of them and track down the problem

**Comment by seladb** [comment] 2019-07-15 21:11
Please let me know how you'd like to proceed. Should we leave this issue open or close it?

**Comment by seladb** [comment] 2019-07-19 23:33
I'm closing this issue for now, please reopen it if needed

**Closed by seladb** 2019-07-19 23:33 UTC
