### ISSUE TITLE
Parse Pcap file 

### ISSUE THREAD

**Issue by fcerkesli** [seladb/PcapPlusPlus#1116] opened 2023-04-05 12:23 UTC
Hello everyone;
I have a pcap file which is generated when I transfered a jpg file between two computers

I used tcpdump at destination computer with this command to generate the pcap file: 
tcpdump -i eth0 -s 0 -w cars.pcap host <HOST_IP> and udp

I used this tftp program to transfer the jpg file: https://tftp.tr.uptodown.com/windows

I am trying to parse pcap file using pcap++ library
I want to filter the frames that only gone from source computer to destination computer
and also take data from that frames and append them one after another

Eventually,I want to export the appended data as another jpg file
In the final: I will compare both jpg files with md5sum to check if there is any loss in the communication line
How can I write that c++ program using pcap++ library?

**Comment by seladb** [comment] 2023-04-06 05:53
PcapPlusPlus does support the FTP protocol, but I'm not sure if TFTP is also supported. @egecetin may know, and he may also know how to extract the data from TFTP packets

**Comment by egecetin** [comment] 2023-04-06 06:39
@fcerkesli @seladb To be honest I don't know the packet structure of _TFTP_, but I checked a pcap with Wireshark and it looks like _FTP_, _TFTP_ uses `opcode + block + data` and _FTP_ uses `command + argument` and sends data over other port. But can't say the `FtpLayer` can directly parse the _TFTP_. It should be modified or should be added a new `TftpLayer`.

For extracting the file from network communication, most of time (for simple cases) the data send sequentially over network and if there is no retransmission (except _TCP_ or custom protocols over _UDP_ and just forget _torrent_, _download manager_ like transfers) you can just dump the payload (I mean really payload you should strip all protocol layers, the part you see as data in wireshark and `PayloadLayer` for PcapPlusPlus) of the communication. But since you want to compare the hashes of the files there is some problem. You should check the RFC of the protocol because there can be end/release message and/or it might send hash at the end of communication or even dummy data padding etc. So, if you can't detect it and dump this data too you can open the file and there will be visually no distortion much (depends to compression of file, for your example it is jpg) but the hash of the file will not match.

Additionally, you can use _**file carving**_ techniques to detect start and end bytes of the file. Check explanation [here](https://resources.infosecinstitute.com/topic/file-carving/). This means you simply look at the payload and search byte patterns. Since explanation is easier, assume you want to extract a html file. 99% of html files start with pattern `<html` (no `>` because you can add options like `<html lang="en">`) and ends with `</html>`. When you detect the start pattern at communication you should start dumping from this byte offset until you detect the end pattern. You can find a wide list for file signatures [here](https://en.wikipedia.org/wiki/List_of_file_signatures) but additional sources exist you can search from google. If you can extract successfully the hashes should match.

And as a side note, for debugging/development using html or txt or similar file might be easier for you. You can find the problems in plain file types easier than in an image file. Compressed files are a bit troublesome.

**Comment by seladb** [comment] 2023-04-06 08:30
Thank you @egecetin for the detailed explanation!
Just one thing to add - if this is TCP data you can use [TCP reassembly](https://pcapplusplus.github.io/docs/features#packet-reassembly) to extract the TCP data in the right order and ignore retransmissions.

Here is an example of how to use TCP reassembly: https://github.com/seladb/PcapPlusPlus/tree/master/Examples/TcpReassembly

**Comment by fcerkesli** [comment] 2023-04-07 08:21
Thank you for the explanation @seladb @egecetin. I tried [this example](https://github.com/seladb/PcapPlusPlus/tree/master/Examples/PcapSplitter) to separate frames from server to client/client to server. I thought this would make data analysis easier. Because only Frames from client to server have DataLayer (as you can see only ...201-...199 have DataLayer. Data equals to UDP payload ). But only the first frame reserved and TFTP protocol appears as UDP when separated (I tried the client-ip and server- ip method). I do not understand why this happened. This is the code I use `./PcapSplitter -f lambo.pcap -o /output/dir -m client-ip`.  If I can split all DataLayers into a single pcap file, I am considering using TCP Reassembly. I am attaching the main pcap file, splitted pcap files and DataLayer images below.

Note: I am using Ubuntu 22.04.2 LTS - Ralease 22.04 - x86_64
Thank you for your help.

Best regards


![11](https://user-images.githubusercontent.com/107847144/230568369-576bce2a-a0b3-47cb-a1e1-d3ec424cf108.png)
![splitted](https://user-images.githubusercontent.com/107847144/230562680-410ec938-2e0a-4210-ad71-2ab1653540fd.png)
![qq](https://user-images.githubusercontent.com/107847144/230564171-3fb54c88-d0c2-4463-82ad-96369c51dde0.jpg)

**Comment by egecetin** [comment] 2023-04-08 16:34
@fcerkesli I'm not sure what happened at pcap splitter. At least it should contain more packets than one according to your screenshots. @seladb Do you have any idea?

**Comment by seladb** [comment] 2023-04-09 02:00
@fcerkesli what are the UDP ports of the first packet?
I can see that the src IP is `.199`, the src port is 36657, and the dest IP is `.201` but I can't see the dst IP.

For the other file it's clear:
`.199` / 62454 -> `.201` / 36657

**Comment by fcerkesli** [comment] 2023-04-09 16:47
@seladb This is the other frame. The frames that has odd numbers, carry 516 bytes of data in splitted pcap files (1-3-5... ).

![123qwe](https://user-images.githubusercontent.com/107847144/230784896-84d10603-468a-4b58-bc8a-5163a64058bb.jpg)

**Comment by seladb** [comment] 2023-04-10 06:30
@fcerkesli I'm not sure I understand... can you share the pcap file? I'll try to run PcapSplitter and see if I can figure out what the issue is. If you don't want to share it here you can send it by email to pcapplusplus@gmail.com

**Comment by seladb** [comment] 2023-04-12 07:25
@fcerkesli and I discussed this offline over email. Here is a short recap: the first packet is TFTP control message that goes to TFTP well-known port (69), and the rest of the packets are data messages (the file transfer) which go over a different (not well-known) port. Hence these are 2 separate streams, that's why PcapSplitter splits them

@fcerkesli please let me know if we close this issue

**Closed** 2023-04-17 06:34 UTC
Labels: question
