### ISSUE TITLE
Multiple cores not assigned for DPDK port packet handling.

### ISSUE THREAD

**Issue by sabhishepalc** [seladb/PcapPlusPlus#212] opened 2019-07-15 10:12 UTC
Snippet while running application "DpdkTrafficFilter":

root@ubuntu:~/PcapPlusPlus/Examples/DpdkExample-FilterTraffic/Bin# ./DpdkTrafficFilter -d 0 -c 15
EAL: Detected 24 lcore(s)
EAL: Probing VFIO support...
EAL:   no supported IOMMU extensions found!
EAL: VFIO support could not be initialized
EAL: PCI device 0000:01:00.0 on NUMA socket -1
EAL:   probe driver: 8086:10d3 net_e1000_em
EAL: PCI device 0000:04:00.0 on NUMA socket -1
EAL:   probe driver: 8086:1583 net_i40e
PMD: eth_i40e_dev_init(): FW 6.0 API 1.7 NVM 06.00.01 eetrack 800035da
EAL: PCI device 0000:04:00.1 on NUMA socket -1
EAL:   probe driver: 8086:1583 net_i40e
Successfully initialized packets pool of size [16383] for device [DPDK_0]
PMD supports the following RSS hash functions : 0x1fbd

PMD support for the modified hash function value: 0xb8

Successfully called rte_eth_dev_configure for device [DPDK_0] with 16 RX queues and 16 TX queues
Successfully initialized 16 RX queues for device [DPDK_0]
Successfully initialized 16 TX queues for device [DPDK_0]
Device [DPDK_0] : Link up; Speed: 40000 Mbps; full-duplex
Using core 1
   Core configuration:
      DPDK device#0: RX-Queue#0;  RX-Queue#1;  RX-Queue#2;  RX-Queue#3;  RX-Queue#4;  RX-Queue#5;
Using core 2
   Core configuration:
      DPDK device#0: RX-Queue#6;  RX-Queue#7;  RX-Queue#8;  RX-Queue#9;  RX-Queue#10;
Using core 3
   Core configuration:
      DPDK device#0: RX-Queue#11;  RX-Queue#12;  RX-Queue#13;  RX-Queue#14;  RX-Queue#15;
New worker thread created
New worker thread created
New worker thread created

---------------------------------------------------------
There were tx queues and rx queues on three cores.

---------------------------------
...

% Produced message (335 bytes), packetlen 66
% Produced message (330 bytes), packetlen 66
% Produced message (330 bytes), packetlen 66
% Produced message (328 bytes), packetlen 66

...
----------------------------------
Application stopped
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| Core ID | Packet Cnt  | Eth Cnt     | ARP Cnt     | IPv4 Cnt    | IPv6 Cnt    | TCP Cnt     | UDP Cnt     | HTTP Cnt    | Matched TCP Flows  | Matched UDP Flows  | Matched Packets    |
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| 1       | 0           | 0           | 0           | 0           | 0           | 0           | 0           | 0           | 0                  | 0                  | 0                  |
| 2       | 47525       | 47525       | 22          | 47501       | 0           | 35424       | 12077       | 521         | 35424              | 12077              | 47525              |
| 3       | 0           | 0           | 0           | 0           | 0           | 0           | 0           | 0           | 0                  | 0                  | 0                  |
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| Total   | 47525       | 47525       | 22          | 47501       | 0           | 35424       | 12077       | 521         | 35424              | 12077              | 47525              |
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

+++++++++++++++++++++++++++++++++++++++++++++++
If we look closely, we have this one core, core 2 to which the packets are directed to
+++++++++++++++++++++++++++++++++++++++++++++++

===========================================================
From the code side, we have changed the following:

- Changed the multiqueue mode.

portConf.rxmode.mq_mode =  ETH_MQ_RX_RSS;

- Modified the rss_key and rss_key_len to 0.

portConf.rx_adv_conf.rss_conf.rss_key = NULL;
portConf.rx_adv_conf.rss_conf.rss_key_len = 0;

- Modified the hash function

portConf.rx_adv_conf.rss_conf.rss_hf = convertRssHfToDpdkRssHf(hashfunction);
//where the has function is:

hashfunction = (ETH_RSS_IPV4 |ETH_RSS_FRAG_IPV4 |ETH_RSS_NONFRAG_IPV4_OTHER | ETH_RSS_NONFRAG_IPV4_TCP | ETH_RSS_NONFRAG_IPV4_UDP ) & port_info.flow_type_rss_offloads;

- In DpdkExample-FilterTraffic, main.cpp:

We hardcoded the no. of TX and RX queues:

 for (vector<DpdkDevice*>::iterator iter = dpdkDevicesToUse.begin(); iter != dpdkDevicesToUse.end(); iter++)
        {
                //if (!(*iter)->openMultiQueues((*iter)->getTotalNumOfRxQueues(), (*iter)->getTotalNumOfTxQueues()))
                if (!(*iter)->openMultiQueues(16,16))
                {
                        EXIT_WITH_ERROR("Couldn't open DPDK device #%d, PMD '%s'", (*iter)->getDeviceId(), (*iter)->getPMDName().c_str());
                }
        }

My query:
=======
@seladb 
Q//How can other cores handle the packets coming on an interface, as we can see that we are putting command for three cores and the logs suggest that the threads were initialized on those cores, any idea why they are not in use?

Thanks in advance, stuck on this one for quite a long time.

Regards,
Abhi

**Comment by echo-Mike** [comment] 2019-07-15 10:34
@sabhishepalc please format your reuest using quote ">" for application output. It is really hard to understand by human eye what You have written.

**Comment by sabhishepalc** [comment] 2019-07-15 11:21
> @sabhishepalc please format your request using quote ">" for application output. It is really hard to understand by human eye what You have written.

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
oot@ubuntu:~/PcapPlusPlus/Examples/DpdkExample-FilterTraffic/Bin# ./DpdkTrafficFilter -d 0 -c 15
EAL: Detected 24 lcore(s)
EAL: Probing VFIO support...
EAL: no supported IOMMU extensions found!
EAL: VFIO support could not be initialized
EAL: PCI device 0000:01:00.0 on NUMA socket -1
EAL: probe driver: 8086:10d3 net_e1000_em
EAL: PCI device 0000:04:00.0 on NUMA socket -1
EAL: probe driver: 8086:1583 net_i40e
PMD: eth_i40e_dev_init(): FW 6.0 API 1.7 NVM 06.00.01 eetrack 800035da
EAL: PCI device 0000:04:00.1 on NUMA socket -1
EAL: probe driver: 8086:1583 net_i40e
Successfully initialized packets pool of size [16383] for device [DPDK_0]
PMD supports the following RSS hash functions : 0x1fbd

PMD support for the modified hash function value: 0xb8

Successfully called rte_eth_dev_configure for device [DPDK_0] with 16 RX queues and 16 TX queues
Successfully initialized 16 RX queues for device [DPDK_0]
Successfully initialized 16 TX queues for device [DPDK_0]
Device [DPDK_0] : Link up; Speed: 40000 Mbps; full-duplex
Using core 1
Core configuration:
DPDK device#0: RX-Queue#0; RX-Queue#1; RX-Queue#2; RX-Queue#3; RX-Queue#4; RX-Queue#5;
Using core 2
Core configuration:
DPDK device#0: RX-Queue#6; RX-Queue#7; RX-Queue#8; RX-Queue#9; RX-Queue#10;
Using core 3
Core configuration:
DPDK device#0: RX-Queue#11; RX-Queue#12; RX-Queue#13; RX-Queue#14; RX-Queue#15;
New worker thread created
New worker thread created
New worker thread created

There were tx queues and rx queues on three cores.

...

% Produced message (335 bytes), packetlen 66
% Produced message (330 bytes), packetlen 66
% Produced message (330 bytes), packetlen 66
% Produced message (328 bytes), packetlen 66

...
Application stopped
| Core ID | Packet Cnt | Eth Cnt | ARP Cnt | IPv4 Cnt | IPv6 Cnt | TCP Cnt | UDP Cnt | HTTP Cnt | Matched TCP Flows | Matched UDP Flows | Matched Packets |
| 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| 2 | 47525 | 47525 | 22 | 47501 | 0 | 35424 | 12077 | 521 | 35424 | 12077 | 47525 |
| 3 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Total | 47525 | 47525 | 22 | 47501 | 0 | 35424 | 12077 | 521 | 35424 | 12077 | 47525 |

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

This is the output of the application including how many packets were handled by each core which I tried to highlight in my last post.

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
***Rest is the details of our modification***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
+++++++++++++++++++++++++++++++++++++++++++++++
If we look closely, we have this one core, core 2 to which the packets are directed to
+++++++++++++++++++++++++++++++++++++++++++++++

===========================================================
From the code side, we have changed the following:

Changed the multiqueue mode.
portConf.rxmode.mq_mode = ETH_MQ_RX_RSS;

Modified the rss_key and rss_key_len to 0.
portConf.rx_adv_conf.rss_conf.rss_key = NULL;
portConf.rx_adv_conf.rss_conf.rss_key_len = 0;

Modified the hash function
portConf.rx_adv_conf.rss_conf.rss_hf = convertRssHfToDpdkRssHf(hashfunction);
//where the has function is:

hashfunction = (ETH_RSS_IPV4 |ETH_RSS_FRAG_IPV4 |ETH_RSS_NONFRAG_IPV4_OTHER | ETH_RSS_NONFRAG_IPV4_TCP | ETH_RSS_NONFRAG_IPV4_UDP ) & port_info.flow_type_rss_offloads;

In DpdkExample-FilterTraffic, main.cpp:
We hardcoded the no. of TX and RX queues:

for (vector<DpdkDevice*>::iterator iter = dpdkDevicesToUse.begin(); iter != dpdkDevicesToUse.end(); iter++)
{
//if (!(*iter)->openMultiQueues((*iter)->getTotalNumOfRxQueues(), (*iter)->getTotalNumOfTxQueues()))
if (!(*iter)->openMultiQueues(16,16))
{
EXIT_WITH_ERROR("Couldn't open DPDK device #%d, PMD '%s'", (*iter)->getDeviceId(), (*iter)->getPMDName().c_str());
}
}

My query:
@seladb
Q//How can other cores handle the packets coming on an interface, as we can see that we are putting command for three cores and the logs suggest that the threads were initialized on those cores, any idea why they are not in use?

Thanks in advance, stuck on this one for quite a long time.

Regards,
Abhi

**Comment by echo-Mike** [comment] 2019-07-15 11:45
@sabhishepalc You have fall to 40GB trap. You need to enable all RSS hash functions supported by Your device plus provide RSS key (in some devices RSS key must be provided by user as default key setup is not correctly implemented by OEM) at least 40 bytes (52 on some devices) long.
Next is not always a correct behaviour:
> Modified the rss_key and rss_key_len to 0.
portConf.rx_adv_conf.rss_conf.rss_key = NULL;
portConf.rx_adv_conf.rss_conf.rss_key_len = 0;

**Comment by sabhishepalc** [comment] 2019-07-16 12:22
> @sabhishepalc You have fall to 40GB trap. You need to enable all RSS hash functions supported by Your device plus provide RSS key (in some devices RSS key must be provided by user as default key setup is not correctly implemented by OEM) at least 40 bytes (52 on some devices) long.
> Next is not always a correct behaviour:
> 
> > Modified the rss_key and rss_key_len to 0.
> > portConf.rx_adv_conf.rss_conf.rss_key = NULL;
> > portConf.rx_adv_conf.rss_conf.rss_key_len = 0;
Hi @echo-Mike ,

Thanks for the reply.
We tried the following as per https://haryachyy.wordpress.com/2019/01/18/learning-dpdk-symmetric-rss/
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
For i40e driver:
>>>>>>>>>>
struct rte_eth_conf port_conf = {
  .rxmode = {
    .mq_mode = ETH_MQ_RX_RSS,
  },
  .rx_adv_conf = {
    .rss_conf = {
        .rss_hf = ETH_RSS_IP |
              ETH_RSS_TCP |
              ETH_RSS_UDP |
              ETH_RSS_SCTP,
    }
   },
};

rte_eth_dev_configure(port_id, rx_queue_num, tx_queue_num, &port_conf);

int sym_hash_enable(int port_id, uint32_t ftype, enum rte_eth_hash_function function)
{
    struct rte_eth_hash_filter_info info;
    int ret = 0;
    uint32_t idx = 0;
    uint32_t offset = 0;

    memset(&info, 0, sizeof(info));

    ret = rte_eth_dev_filter_supported(port_id, RTE_ETH_FILTER_HASH);
    if (ret < 0) {
        DPDK_ERROR("RTE_ETH_FILTER_HASH not supported on port: %d",
                         port_id);
        return ret;
    }

    info.info_type = RTE_ETH_HASH_FILTER_GLOBAL_CONFIG;
    info.info.global_conf.hash_func = function;

    idx = ftype / UINT64_BIT;
    offset = ftype % UINT64_BIT;
    info.info.global_conf.valid_bit_mask[idx] |= (1ULL << offset);
    info.info.global_conf.sym_hash_enable_mask[idx] |=
                        (1ULL << offset);

    ret = rte_eth_dev_filter_ctrl(port_id, RTE_ETH_FILTER_HASH,
                                  RTE_ETH_FILTER_SET, &info);
    if (ret < 0)
    {
        DPDK_ERROR("Cannot set global hash configurations"
                        "on port %u", port_id);
        return ret;
    }

    return 0;
}

int sym_hash_set(int port_id, int enable)
{
    int ret = 0;
    struct rte_eth_hash_filter_info info;

    memset(&info, 0, sizeof(info));

    ret = rte_eth_dev_filter_supported(port_id, RTE_ETH_FILTER_HASH);
    if (ret < 0) {
        DPDK_ERROR("RTE_ETH_FILTER_HASH not supported on port: %d",
                         port_id);
        return ret;
    }

    info.info_type = RTE_ETH_HASH_FILTER_SYM_HASH_ENA_PER_PORT;
    info.info.enable = enable;
    ret = rte_eth_dev_filter_ctrl(port_id, RTE_ETH_FILTER_HASH,
                        RTE_ETH_FILTER_SET, &info);

    if (ret < 0)
    {
        DPDK_ERROR("Cannot set symmetric hash enable per port "
                        "on port %u", port_id);
        return ret;
    }

    return 0;
}

sym_hash_enable(port_id, RTE_ETH_FLOW_NONFRAG_IPV4_TCP, RTE_ETH_HASH_FUNCTION_TOEPLITZ);
sym_hash_enable(port_id, RTE_ETH_FLOW_NONFRAG_IPV4_UDP, RTE_ETH_HASH_FUNCTION_TOEPLITZ);
sym_hash_enable(port_id, RTE_ETH_FLOW_FRAG_IPV4, RTE_ETH_HASH_FUNCTION_TOEPLITZ);
sym_hash_enable(port_id, RTE_ETH_FLOW_NONFRAG_IPV4_SCTP, RTE_ETH_HASH_FUNCTION_TOEPLITZ);
sym_hash_enable(port_id, RTE_ETH_FLOW_NONFRAG_IPV4_OTHER, RTE_ETH_HASH_FUNCTION_TOEPLITZ);

sym_hash_set(port_id, 1);

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Before applying the above:

With the first one of explicit RSS key - the output is:

Application stopped

| Core ID | Packet Cnt  | Eth Cnt     | ARP Cnt     | IPv4 Cnt    | IPv6 Cnt    | TCP Cnt     | UDP Cnt     | HTTP Cnt    | Matched TCP Flows  | Matched UDP Flows  | Matched Packets    |

| 1       | 165343      | 165343      | 24          | 165308      | 0           | 121466      | 43842       | 1878        | 121466             | 43842              | 165343             |
| 2       | 0           | 0           | 0           | 0           | 0           | 0           | 0           | 0           | 0                  | 0                  | 0                  |
| 3       | 0           | 0           | 0           | 0           | 0           | 0           | 0           | 0           | 0                  | 0                  | 0                  |
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
| Total   | 165343      | 165343      | 24          | 165308      | 0           | 121466      | 43842       | 1878        | 121466             | 43842              | 165343             |



With the second approach of installing the appropriate hash function for the i40e drivers:

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Application stopped


| Core ID | Packet Cnt  | Eth Cnt     | ARP Cnt     | IPv4 Cnt    | IPv6 Cnt    | TCP Cnt     | UDP Cnt     | HTTP Cnt    | Matched TCP Flows  | Matched UDP Flows  | Matched Packets    |

| 1       | 0           | 0           | 0           | 0           | 0           | 0           | 0           | 0           | 0                  | 0                  | 0                  |
| 2       | 111217      | 111217      | 24          | 111191      | 0           | 80401       | 30790       | 1131        | 80401              | 30790              | 111217             |
| 3       | 0           | 0           | 0           | 0           | 0           | 0           | 0           | 0           | 0                  | 0                  | 0                  |
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
| Total   | 111217      | 111217      | 24          | 111191      | 0           | 80401       | 30790       | 1131        | 80401              | 30790              | 111217             |

My Query:
----------
@echo-Mike, can you suggest what is going wrong in this? And how we can write this to achieve the multicore functionality?

**Comment by echo-Mike** [comment] 2019-07-16 12:54
@sabhishepalc at first next setup works for me:
```C++
// Struct with description of port that will be setupped
// may be obtained prior to call to rte_eth_dev_configure
// by calling rte_eth_dev_info_get
struct rte_eth_dev_info devInfo;

struct rte_eth_conf portConf = {
    .rxmode = {
        .mq_mode = ETH_MQ_RX_RSS,
    },
    .rx_adv_conf = {
        .rss_conf = {
            .rss_key = NULL, // use default RSS key provided by OEM
            .rss_key_len = 40, // this may be 56 if 40 don't work
            .rss_hf = devInfo.flow_type_rss_offloads & ETH_RSS_PROTO_MASK
        }
    },
};
```
I have never used the `rte_eth_dev_filter_*` API. I think it is not related to RSS but to FDIR filter setup (see your NIC configuration guide for more information about FDIR setup).

**Comment by sabhishepalc** [comment] 2019-07-17 06:17
> @sabhishepalc at first next setup works for me:
> 
> ```c++
> // Struct with description of port that will be setupped
> // may be obtained prior to call to rte_eth_dev_configure
> // by calling rte_eth_dev_info_get
> struct rte_eth_dev_info devInfo;
> 
> struct rte_eth_conf portConf = {
>     .rxmode = {
>         .mq_mode = ETH_MQ_RX_RSS,
>     },
>     .rx_adv_conf = {
>         .rss_conf = {
>             .rss_key = NULL, // use default RSS key provided by OEM
>             .rss_key_len = 40, // this may be 56 if 40 don't work
>             .rss_hf = devInfo.flow_type_rss_offloads & ETH_RSS_PROTO_MASK
>         }
>     },
> };
> ```
> 
> I have never used the `rte_eth_dev_filter_*` API. I think it is not related to RSS but to FDIR filter setup (see your NIC configuration guide for more information about FDIR setup).

Hello @echo-Mike ,

>>Tried it with the suggestion of keeping the key-len as 56 but I am still processing only on one core.
>>I understand the RSS hash function is used load balancing the packets received on the NIC across RX queues handled by several logical cores, is there any other factor influencing the queue handling process:

I mean,
1. In our setup, we have different types of traffic as seen from the output, but the DPDK port will receive all these traffic with VXLAN header. 

The DPDK application strips the VXLAN header and then processes the packets. Since all the packets received are VXLAN packets, the processing is done only by one core.

Does the type of traffic counts?

2. In our tests, the NIC does not support IPv6 RSS like ETH_RSS_IPV6 and therefore, we have kept our RSS hash function. 

( ETH_RSS_VXLAN |ETH_RSS_FRAG_IPV4 |ETH_RSS_NONFRAG_IPV4_OTHER | ETH_RSS_NONFRAG_IPV4_TCP | ETH_RSS_NONFRAG_IPV4_UDP ) & port_info.flow_type_rss_offloads

Can you suggest, how can we improve the function?

@echo-Mike , thanks a lot for your cooperation.

**Comment by echo-Mike** [comment] 2019-07-17 07:55
Maybe the VXLAN encapsulation is the source of an issue.
Let us look on the VXLAN packet:
![image](https://user-images.githubusercontent.com/14947581/61357058-392c5e00-a880-11e9-898a-b948d169b9e3.png)
The NIC is only capable (on high speeds in most cases) of automatically parse the __Outer Ethernet__, __Outer IP__ and __Outer UDP__ layers. The hash functions will be applied to thouse parsed layers (a.e. the RSS is based on paramenters of __Outer Ethernet__, __Outer IP__ and __Outer UDP__ NOT on _Inner Ethernet_, _Inner IP_).
I suggest to directly look at `packet_type` field of `mbuf` to understand what types of trafic Your particular NIC is capable to parse in stone (check `packet_type` field against predefined set of macro constants `RTE_PTYPE_*` located in `rte_mbuf_ptype.h`)
![image](https://user-images.githubusercontent.com/14947581/61357464-06369a00-a881-11e9-90f6-4c760ae0161e.png)

**Comment by echo-Mike** [comment] 2019-07-17 08:05
As an unbiased observation: most NICs (especially 40/100GB) do not correctly/reliably implement hardware packet parsing. In most cases the packets that can't be parsed will be put to RX queue 1 (or 0) or simply dropped.

**Comment by sabhishepalc** [comment] 2019-07-19 11:38
Hello @echo-Mike ,

I changed my code as per your suggestion:
//Changes
struct ether_hdr *eth_hdr;
        uint16_t eth_type;
        uint64_t ol_flags;
        uint16_t i, packet_type;
        uint16_t is_encapsulation;
        char buf[256];
        struct rte_net_hdr_lens hdr_lens;
        uint32_t sw_packet_type;
 
uint16_t DpdkDevice::receivePackets(.. function in DpdkDevice.cpp
 
        for (size_t index = 0; index < packetsReceived; ++index)
        {
                struct rte_mbuf* mBuf = mBufArray[index];

//New code to identify packet type and hash.

                struct rte_mbuf* mb = mBufArray[index];

                eth_hdr = rte_pktmbuf_mtod(mb, struct ether_hdr *);
                eth_type = rte_be_to_cpu_16(eth_hdr->ether_type);
                ol_flags = mb->ol_flags;
                packet_type = mb->packet_type;
                LOG_ERROR(" - RSS hash=0x%x\n", (unsigned int) mb->hash.rss);

                if (ol_flags & PKT_RX_FDIR) {
				LOG_ERROR(" - FDIR matched ");
				if (ol_flags & PKT_RX_FDIR_ID)
				LOG_ERROR("ID=0x%x",
				mb->hash.fdir.hi);
				else if (ol_flags & PKT_RX_FDIR_FLX)
				LOG_ERROR("flex bytes=0x%08x %08x",
				mb->hash.fdir.hi, mb->hash.fdir.lo);
				else
				LOG_ERROR("hash=0x%x ID=0x%x ",
				mb->hash.fdir.hash, mb->hash.fdir.id);
				}

				if (ol_flags & PKT_RX_VLAN_STRIPPED)
				LOG_ERROR(" - VLAN tci=0x%x", mb->vlan_tci);
				if (ol_flags & PKT_RX_QINQ_STRIPPED)
				LOG_ERROR(" - QinQ VLAN tci=0x%x, VLAN tci outer=0x%x",
				mb->vlan_tci, mb->vlan_tci_outer);
				if (mb->packet_type) {
				rte_get_ptype_name(mb->packet_type, buf, sizeof(buf));
				LOG_ERROR(" - hw ptype: %s", buf);
				}
				sw_packet_type = rte_net_get_ptype(mb, &hdr_lens,
				RTE_PTYPE_ALL_MASK);
				rte_get_ptype_name(sw_packet_type, buf, sizeof(buf));
				LOG_ERROR(" - sw ptype: %s", buf);
				if (sw_packet_type & RTE_PTYPE_L2_MASK)
				LOG_ERROR(" - l2_len=%d", hdr_lens.l2_len);
				if (sw_packet_type & RTE_PTYPE_L3_MASK)
				LOG_ERROR(" - l4_len=%d", hdr_lens.l4_len);
				if (sw_packet_type & RTE_PTYPE_TUNNEL_MASK)
				LOG_ERROR(" - tunnel_len=%d", hdr_lens.tunnel_len);
				if (sw_packet_type & RTE_PTYPE_INNER_L2_MASK)
				LOG_ERROR(" - inner_l2_len=%d", hdr_lens.inner_l2_len);
				if (sw_packet_type & RTE_PTYPE_INNER_L4_MASK)
				LOG_ERROR(" - inner_l4_len=%d", hdr_lens.inner_l4_len);


As suspected, we are getting the following results of the test:

//Getting the same RSS hash value for all our packets.

% Produced message (330 bytes), packetlen 66
% Produced message (330 bytes), packetlen 66
% Produced message (335 bytes), packetlen 70
% Produced message (330 bytes), packetlen 66
% Produced message (277 bytes), packetlen 150
% Produced message (277 bytes), packetlen 150
RSS hash=0x4f042ce7

hw ptype: L2_ETHER L3_IPV4_EXT_UNKNOWN L4_UDP
sw ptype: L2_ETHER_VLAN L3_IPV4 L4_UDP
l2_len=18
l4_len=8
% Produced message (276 bytes), packetlen 150
RSS hash=0x4f042ce7

hw ptype: L2_ETHER L3_IPV4_EXT_UNKNOWN L4_UDP
sw ptype: L2_ETHER_VLAN L3_IPV4 L4_UDP
l2_len=18
l4_len=8
% Produced message (276 bytes), packetlen 150
RSS hash=0x4f042ce7

hw ptype: L2_ETHER L3_IPV4_EXT_UNKNOWN L4_UDP
sw ptype: L2_ETHER_VLAN L3_IPV4 L4_UDP
l2_len=18
l4_len=8
% Produced message (276 bytes), packetlen 104
RSS hash=0x4f042ce7

hw ptype: L2_ETHER L3_IPV4_EXT_UNKNOWN L4_UDP
sw ptype: L2_ETHER_VLAN L3_IPV4 L4_UDP
l2_len=18
l4_len=8
% Produced message (276 bytes), packetlen 104
RSS hash=0x4f042ce7

hw ptype: L2_ETHER L3_IPV4_EXT_UNKNOWN L4_UDP
sw ptype: L2_ETHER_VLAN L3_IPV4 L4_UDP
l2_len=18
l4_len=8
% Produced message (276 bytes), packetlen 104
RSS hash=0x4f042ce7

Queries:
>>>>>>>
-> Just wanted to ask if RSS hash would be modified if we modify the UDP port numbers in the vxlan tunnels.
-> Anything else on our mind, we can do?

Thanks @echo-Mike a lot.

**Comment by echo-Mike** [comment] 2019-07-19 13:29
Hi @sabhishepalc. As You may see from output provided my position on insufficient packet parsing on NIC is confirmed (RSS hash is equal for each message).
Answering Your questions:
1. If Your NIC advertise support of `ETH_RSS_NONFRAG_IPV4_UDP` or `ETH_RSS_NONFRAG_IPV6_UDP` or `ETH_RSS_IPV6_UDP_EX` it MAY help. In Your situation NIC is better to be capable of `ETH_RSS_VXLAN`.
2. You may use simple VLAN/QnQ to signify types of trafic

For the future please use GitHub built-in code formating engine via \```C++ you_code_here``` construct. It is realy hard to understand Your code without copy-pasting it to the code editor.

**Comment by echo-Mike** [comment] 2019-07-24 08:08
Hey @sabhishepalc. What is the status of Your requests? Can this issue be closed now? As it is not realy a PcapPlusPlus issue.

**Comment by echo-Mike** [comment] 2019-07-25 07:08
Hey @seladb! I think this issue can be closed now and reopened by the @sabhishepalc later.
__Reason__: The issue is not in the domain of __PcapPlusPlus__

**Comment by seladb** [comment] 2019-07-25 07:23
thanks @echo-Mike , I'll close the issue now. Please reopen it if needed

**Closed by seladb** 2019-07-25 07:23 UTC
Labels: 3rd-party
