### ISSUE TITLE
PcapNgFileReader returns 0 for all timestamps

### ISSUE THREAD

**Issue by JordanHolland** [seladb/PcapPlusPlus#624] opened 2021-04-07 13:57 UTC
Hi! Really cool library. I'm having some trouble reading a standard `pcapng` file with the `PcapNgFileReader`.

Every timestamp returned by `getPacketTimeStamp()` has both the `tv_sec` and `tv_nsec` set to `0`. Below is the simplest version of the code to reproduce the bug:

```
#include <Packet.h>
#include "PacketUtils.h"
#include <PcapFileDevice.h>

int main(int argc, char **argv) {
    std::string comment;
    pcpp::RawPacket rp;
    pcpp::PcapNgFileReaderDevice reader(argv[1]);

    reader.open();
    while(reader.getNextPacket(rp, comment)) {
        printf("seconds: %ld, nanoseconds: %ld\n", rp.getPacketTimeStamp().tv_sec, rp.getPacketTimeStamp().tv_nsec);
    }
}
```

Further, I've checked that the timestamps in the file are in fact there through tcpdump:

```
$ tcpdump -r snowflake-dataset.pcapng -nnn | head
reading from file snowflake-dataset.pcapng, link-type EN10MB (Ethernet)
20:55:01.332173 IP 192.168.1.26.51945 > 104.153.85.171.50001: UDP, length 155
20:55:01.401324 IP 192.168.1.26.51945 > 104.153.85.171.50001: UDP, length 155
20:55:01.440117 IP 104.153.85.171.50001 > 192.168.1.26.51945: UDP, length 1280
20:55:01.440879 IP 104.153.85.171.50001 > 192.168.1.26.51945: UDP, length 1215
20:55:01.442268 IP 192.168.1.26.51945 > 104.153.85.171.50001: UDP, length 580
20:55:01.485630 IP 104.153.85.171.50001 > 192.168.1.26.51945: UDP, length 579
10:13:18.455125 IP 192.168.1.17.56562 > 213.179.197.231.50012: UDP, length 155
10:13:18.523866 IP 192.168.1.17.56562 > 213.179.197.231.50012: UDP, length 155
10:13:18.562697 IP 213.179.197.231.50012 > 192.168.1.17.56562: UDP, length 1280
10:13:18.564248 IP 213.179.197.231.50012 > 192.168.1.17.56562: UDP, length 1215
tcpdump: Unable to write output: Broken pipe
```

And through tshark:

```
$ tshark -n -T fields -e frame.time -r snowflake-dataset.pcapng | head
Jun  8, 2020 20:55:01.332173000 EDT
Jun  8, 2020 20:55:01.401324000 EDT
Jun  8, 2020 20:55:01.440117000 EDT
Jun  8, 2020 20:55:01.440879000 EDT
Jun  8, 2020 20:55:01.442268000 EDT
Jun  8, 2020 20:55:01.485630000 EDT
Jun  9, 2020 10:13:18.455125000 EDT
Jun  9, 2020 10:13:18.523866000 EDT
Jun  9, 2020 10:13:18.562697000 EDT
Jun  9, 2020 10:13:18.564248000 EDT
```

I've also attached the packet trace for reference.
[snowflake-dataset.pcapng.gz](https://github.com/seladb/PcapPlusPlus/files/6272087/snowflake-dataset.pcapng.gz)

This certainly could be my misuse of the API, if so please let me know! 

Thanks.

**Comment by seladb** [comment] 2021-04-08 07:18
hi @JordanHolland !
It took me a while but I found the issue - it's a limitation in `LightPcapNg` which is the 3rd party library used in PcapPlusPlus for parsing pcapng files. The issue is in this line:
https://github.com/seladb/PcapPlusPlus/blob/3b8c9ef5fbab28cc406b4e6b894be0c6e7118cd4/3rdParty/LightPcapNg/LightPcapNg/include/light_pcapng_ext.h#L46

`LightPcapNg` supports a maximum number of 32 interfaces but your pcapng file has approximately 2000 interfaces:

![image](https://user-images.githubusercontent.com/9059541/113983685-0fa72900-97ff-11eb-9461-b41a5eba3122.png)

After I changed this number from 32 to 2000 all timestamps worked, however I don't think it's wise to change it because this will cause a lot more memory to be allocated:
https://github.com/seladb/PcapPlusPlus/blob/3b8c9ef5fbab28cc406b4e6b894be0c6e7118cd4/3rdParty/LightPcapNg/LightPcapNg/include/light_pcapng_ext.h#L73-L74

Do you think you can change your pcapng file to contain less interfaces?

**Comment by JordanHolland** [comment] 2021-04-09 13:11
Thanks for hunting this down. I'll need to think a bit about the feasibility of limiting the number of interfaces in each `pcapng` for our purposes. Either way, understanding the origin of this error is incredibly helpful.

**Comment by seladb** [comment] 2021-04-12 06:07
@JordanHolland should we keep this issue open or can we close it?

**Comment by JordanHolland** [comment] 2021-04-12 15:06
Issue is good to close. Thanks for your help. For your reference, changing the interface block max to 2000 (from 32) increases the memory usage from 2MB to 6MB.

**Closed** 2021-04-13 05:45 UTC
Labels: wontfix
