### ISSUE TITLE
Problem While Setting Up libraries of the PcapPlusPlus.

### ISSUE THREAD

**Issue by egeSPACEoztas** [seladb/PcapPlusPlus#627] opened 2021-04-08 15:23 UTC
Hello, me and my friends decided to use PcapPlusPlus for one of our school projects.

But I can’t seem to correctly set up an example project. I suppose there is probably a very important step I am overlooking.

I am trying to set up the pre-compiled version of PcapPlusPlus, and I think I have followed the instructions pretty closely. But once I open the solution I see no libraries in the project and all of the special PcapPlusPluss code snips showing errors.

Maybe I did something wrong when setting up the property sheet but everything seems solid there.

README file mentions choosing versions of the program but I haven’t encountered anything like that. So I suppose that is how you actually add the libraries into the project. But I am not sure what I am missing here. When readme file told me to load/build the solution I opened it using visual studio. Maybe there was something else I had to do.

 

I am sure this is most obvious to a more experienced programmer but I can’t seem to do this correctly. What am I doing wrong?

If you can help that would be much appreciated.

**Comment by seladb** [comment] 2021-04-09 07:07
hi @egeSPACEoztas , thanks for reaching out!
Since you're trying to use the pre-compiled version of PcapPlusPlus, when you download the zip file (for example [`pcapplusplus-20.08-windows-vs2019.zip`](https://github.com/seladb/PcapPlusPlus/releases/download/v20.08/pcapplusplus-20.08-windows-vs2019.zip)) you can find a `README.release` file inside that contains detailed instructions on how to run the example app. Have you followed the instructions in this file?

**Comment by egeSPACEoztas** [comment] 2021-04-09 09:00
Thanks for responding. 

I've re-read the readme.txt file and now I definitely believe I did some thing wrong or overlooked something but the problem is I don't understand what I missed.

I believe I have the all the required programs and correctly liked them in the `PcapPlusPlusPropertySheet.props` file.

Currently I am trying to work with the example project but There is no libraries linked in it or any configuration files under Examples folder. I think I have to link the tree libraries manually, but I can't find any resources on how to do them. At least those which I am able to follow. 

Can you explain how can I add the pcapplusplus libraries to the project?

**Comment by seladb** [comment] 2021-04-09 09:55
There shouldn't be any configuration file. The `ExampleProject.vcxproj` and `PcapPlusPlusPropertySheet.props` files contain all the relevant configurations (you can open them with a text editor to view them in Visual Studio).
I'm not sure what you mean by "There is no libraries linked" - the pre-compiled libraries are under `x86\Debug`, `x86\Release`, `x64\Debug`, `x64\Release` and `ExampleProject.vcxproj` points to these directories, depends on the x86/x64 and Debug/Release configuration you choose in Visual Studio.

Did you try to simply build the project? What error do you get?

**Comment by egeSPACEoztas** [comment] 2021-04-09 10:17
The error I get when I try to build is:
`Cannot open include file: 'IPv4Layer.h': No such file or directory.`

I know the libraries are in those file locations but when I open the project there isn't any library files showing up on the solution explorer. Additionally all of the `#include <...>` lines on example projects main.cpp file are showing errors saying `cannot open source  file "..." `
`

**Comment by seladb** [comment] 2021-04-09 10:24
I'll try to reproduce it on my local machine. Which Visual Studio version are you using?
Also - are you using the latest version of PcapPlusPlus (v20.08)?

**Comment by egeSPACEoztas** [comment] 2021-04-09 10:30
I am using visual studio 2019 and PcapPlusPlus (v20.08)

**Comment by seladb** [comment] 2021-04-12 06:54
I reproduced all the steps mentioned in the `README.release` file inside of the zip file [`pcapplusplus-20.08-windows-vs2019.zip`](https://github.com/seladb/PcapPlusPlus/releases/download/v20.08/pcapplusplus-20.08-windows-vs2019.zip) in a fresh Windows VM and things are working for me. Here is what I did:

1. Downloaded PcapPlusPlus v20.08, [WinPcap Dev Pack](https://www.winpcap.org/devel.htm) and [pthreads](https://github.com/seladb/PcapPlusPlus-Deploy/raw/master/Packages/pthreads-w32-2-9-1-release.zip)
2. Extracted the zip file
3. Edited the props file: `C:\Users\IEUser\Downloads\pcapplusplus-20.08-windows-vs2019\ExampleProject\PcapPlusPlusPropertySheet.props`:
  
   ![image](https://user-images.githubusercontent.com/9059541/114351607-b2bdb280-9b1f-11eb-93ae-2fd9e4c1e2bc.png)

4. Opened the sln file in VS 2019: `C:\Users\IEUser\Downloads\pcapplusplus-20.08-windows-vs2019\ExampleProject\ExampleProject.sln` and tried to build the solution. At this point I got a lot of errors:
   
   ![image](https://user-images.githubusercontent.com/9059541/114351962-22cc3880-9b20-11eb-9806-631f3f8f1321.png)

5. I followed the steps mentioned in `README.release`:
```text
   - Right click on `ExampleProject` project -> Choose "Properties"
   - Go to "Configuration Properties" -> "General"
   - Open the drop down list next to "Windows SDK version" and choose the version installed on your machine
```

   ![image](https://user-images.githubusercontent.com/9059541/114352420-b3a31400-9b20-11eb-87e5-f652835dc16e.png)


6. I rebuilt the solution, everything is working now:

   ![image](https://user-images.githubusercontent.com/9059541/114352650-f664ec00-9b20-11eb-80c7-f15a68eeb3d4.png)


Please try to follow the same steps and let me know if it's working for you.

**Comment by egeSPACEoztas** [comment] 2021-04-14 18:05
I am a little busy at the moment but once I try what you've posted once I have the time.

**Comment by seladb** [comment] 2021-04-15 06:48
thanks @egeSPACEoztas . I'll close this issue for now, please reopen if needed

**Closed by seladb** 2021-04-15 06:48 UTC
Labels: question
